#!/bin/bash

# System stuff
alias cp="cp -i"                          # confirm before overwriting something
alias df="df -h"                          # human-readable sizes
alias free="free -h"                      # human-readable sizes
{%@@ if distro_id == "pop" or distro_id == "ubuntu" @@%}
alias cat="batcat"
{%@@ else @@%}
alias cat="bat"
{%@@ endif @@%}
alias l='lsd --group-dirs first --date=+"%d.%m.%Y %H:%M" -F'
alias ls='l'
alias ll='l -lh'
alias la='l -la'

alias crontab='crontab -i'

# Emacs
alias evil="emacsclient -nc -a ''"
alias vil="emacsclient -t"

# Pacman
alias fixit="sudo rm -f /var/lib/pacman/db.lck"
alias inst="sudo pacman -S"
alias uninst="sudo pacman -Rsu"
alias mirrors="sudo pacman-mirrors -g"

# Config
alias con="$EDITOR $HOME/.config/i3/config"
alias comp="$EDITOR $HOME/.config/compton.conf"
alias printer="system-config-printer"
alias bashrc="$EDITOR $HOME/.bashrc"
alias zshrc="$EDITOR $HOME/.zshrc"
alias fishrc="$EDITOR $HOME/.config/fish/config.fish"

# Dotdrop for dotfiles
alias dotdrop='eval (grep -v "^#" ~/dotfiles/.env) $DOTREPO/dotdrop.sh'
alias dotgit="git -C $DOTREPO"
#alias dotsync="dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install"

# Translates
alias tde="trans :de"
alias ten="trans :en"
alias tfr="trans :fr"

# Programs
alias zt="zathura --fork"
alias xclip="xclip -selection c"
alias xopen="xdg-open"
alias nfetch="neofetch --w3m"
alias feh="feh --scale-down --start-at"
alias pokerstars="wine .wine/drive_c/Program\ Files\ \(x86\)/PokerStars.EU/PokerStarsUpdate.exe"

# Python things
alias ipylab="ipython --pylab"
alias p="ipython --pdb"
alias xpython='xvfb-run --auto-servernum -s "-screen 0 1400x900x24" python'

# Julia things
alias jnb="julia --project=. -e 'using IJulia; notebook(dir=\".\")'"
alias j="julia --project=."
alias pluto="julia --project=@Pluto -e 'using Pluto; Pluto.run()'"

# Misc
alias lenny="echo -n \"( ͡° ͜ʖ ͡°)\" | xclip"
alias lazyvf="vf activate lazy"
alias papers="ranger ~/MEGA/papers/lib/"
