#!/bin/bash
alias cp="cp -i"                          # confirm before overwriting something                 
alias df="df -h"                          # human-readable sizes
alias free="free -h"                      # human-readable sizes
alias np="$EDITOR -w PKGBUILD"
alias more=less
alias cat=bat
alias evil="emacsclient -nc"
alias vil="emacsclient -t"
alias zt="zathura --fork"
alias xclip="xclip -selection c"

alias con="$EDITOR $HOME/.i3/config"
alias comp="$EDITOR $HOME/.config/compton.conf"
alias fixit="sudo rm -f /var/lib/pacman/db.lck"
alias inst="sudo pacman -S"
alias uninst="sudo pacman -Rsu"
alias la='ls -la --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias ll='ls -l --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias l='ls --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias mirrors="sudo pacman-mirrors -g"
alias printer="system-config-printer"
alias xopen="xdg-open"
alias nfetch="neofetch --w3m"

alias bashrc="$EDITOR $HOME/.bashrc"
alias zshrc="$EDITOR $HOME/.zshrc"
alias fishrc="$EDITOR $HOME/.config/fish/config.fish"

alias ausgaben="vim '+normal Go' +startinsert scp://ovh//home/nath/Documents/ausgaben.csv"
alias einnahmen="vim '+normal Go' +startinsert scp://ovh//home/nath/Documents/einnahmen.csv"

alias dotdrop="$DOTREPO/dotdrop.sh"
alias dotgit="git -C $DOTREPO"
#alias dotsync="dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install"

# Translates
alias tde="trans :de"
alias ten="trans :en"
alias tfr="trans :fr"

alias feh="feh --scale-down --start-at"

# Python things
alias ipylab="ipython --pylab"
alias p="ipython --pdb"

alias lenny="echo -n \"( ͡° ͜ʖ ͡°)\" | xclip"
alias pokerstars="wine .wine/drive_c/Program\ Files\ \(x86\)/PokerStars.EU/PokerStarsUpdate.exe"

alias lazyvf="vf activate lazy"
alias papers="ranger ~/MEGA/papers/lib/"
