#!/bin/bash
# System stuff
alias cp="cp -i"                          # confirm before overwriting something
alias df="df -h"                          # human-readable sizes
alias free="free -h"                      # human-readable sizes
# alias cat=bat
alias la='ls -la --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias ll='ls -l --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias l='ls --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'

# Emacs
alias evil="emacsclient -nc"
alias vil="emacsclient -t"

# Pacman
alias fixit="sudo rm -f /var/lib/pacman/db.lck"
alias inst="sudo pacman -S"
alias uninst="sudo pacman -Rsu"
alias mirrors="sudo pacman-mirrors -g"

# Config files
#alias con="$EDITOR $HOME/.i3/config"
alias con="$EDITOR $HOME/.config/i3/config"
alias comp="$EDITOR $HOME/.config/compton.conf"
alias bashrc="$EDITOR $HOME/.bashrc"
alias zshrc="$EDITOR $HOME/.zshrc"
alias fishrc="$EDITOR $HOME/.config/fish/config.fish"

# Misc
alias printer="system-config-printer"
alias xopen="xdg-open"
alias nfetch="neofetch --w3m"
# Dotdrop for dotfiles
alias dotdrop="$DOTREPO/dotdrop.sh"
alias dotgit="git -C $DOTREPO"
