#
# ~/.bash_profile
#

export PATH="$PATH:/home/nath/.local/bin"

[[ -f ~/.bashrc ]] && . ~/.bashrc

[[ -f ~/.cargo/env ]] && . ~/.cargo/env

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

case ":$PATH:" in *:$HOME/.julia/juliaup/bin:*);; *)
    export PATH=$HOME/.julia/juliaup/bin${PATH:+:${PATH}};;
esac

# <<< juliaup initialize <<<
