#
# ~/.bashrc
#

[[ $- != *i* ]] && return

[[ -f ~/.extend.bashrc ]] && . ~/.extend.bashrc
[[ -f ~/.profile ]] && . ~/.profile

[ -r /usr/share/bash-completion/bash_completion   ] && . /usr/share/bash-completion/bash_completion


## Master Password App
[[ -f ~/.mpw ]] && . ~/.mpw


## BASH IS BAD
if command -v fish >/dev/null; then
    exec fish
elif command -v zsh >/dev/null; then
    exec zsh
fi
