#
# ~/.bash_profile
#

export PATH="$PATH:/home/nath/.local/bin"
export PATH="$HOME/.cargo/bin:$PATH"

[[ -f ~/.bashrc ]] && . ~/.bashrc

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

case ":$PATH:" in *:/home/nbosch/.julia/juliaup/bin:*);; *)
    export PATH=/home/nbosch/.julia/juliaup/bin${PATH:+:${PATH}};;
esac

# <<< juliaup initialize <<<
