#+TITLE: Literate Spacemacs Config with Org-babel
#+PROPERTY: header-args :results silent

* Table of Contents   :TOC:
- [[#general-emacs-settings][General Emacs settings]]
  - [[#hotkey-to-modify-this-config-file][Hotkey to modify this config file.]]
  - [[#i-like-visual-line-mode][I like visual line mode]]
  - [[#smoother-undo-behavior][Smoother undo behavior]]
  - [[#better-vertical-splitting][Better vertical splitting]]
  - [[#comment-regionline-with-c-s-c][Comment region/line with "C-S-c"]]
  - [[#larger-scroll-margin][Larger scroll margin]]
  - [[#pdfs][PDFs]]
    - [[#fit-pdf-page-to-frame][Fit PDF page to frame]]
    - [[#pdf-dark-mode-to-fit-the-gruvbox-theme][PDF: Dark mode to fit the gruvbox theme]]
  - [[#auto-refresh-buffers-when-files-changed-on-disk][Auto-refresh buffers when files changed on disk]]
  - [[#libnotify-to-display-notifications][~libnotify~ to display notifications]]
  - [[#show-time-and-date-in-modeline][Show time and date in modeline]]
  - [[#pop-up-shell][Pop-up shell]]
  - [[#auth-info][Auth-info]]
  - [[#nicer-treemacs][Nicer ~treemacs~]]
  - [[#emacs-i3-window-movement-integration][Emacs-i3 window movement integration]]
  - [[#increase-numbers-with-the-same-hotkeys-as-in-vim][Increase numbers with the same hotkeys as in vim]]
  - [[#better-eshell-usage][Better eshell usage]]
  - [[#visible-bell-instead-of-ringing-bell][Visible bell instead of ringing bell]]
  - [[#do-not-start-emacs-with-a-warnings-buffer-open][Do not start emacs with a warnings buffer open]]
- [[#organize-my-life-with-org-mode][Organize my life with ~org-mode~]]
  - [[#general-settings][General settings]]
    - [[#prettier-org][Prettier org]]
      - [[#inline-images][Inline images]]
      - [[#pretty-entities][Pretty entities]]
      - [[#hide-emphasis-markers-for-increased-prettiness][Hide emphasis markers, for increased prettiness]]
      - [[#link-abbreviations][Link Abbreviations]]
    - [[#enforce-todo-dependencies][Enforce todo dependencies]]
    - [[#autosave-org-files][Autosave org files]]
    - [[#archive-tag-to-gray-out-things-i-do-not-need][Archive tag to gray out things I do not need]]
    - [[#project-tag-do-not-inherit]["project" tag: Do not inherit]]
    - [[#start-org-with-some-useful-modes][Start org with some useful modes]]
    - [[#column-view][Column view]]
    - [[#priorities][Priorities]]
    - [[#make-search-work-again][Make search work again]]
    - [[#insert-emojis][Insert emojis]]
  - [[#org-refile-targets][~org-refile~ targets]]
  - [[#keywords][keywords]]
  - [[#org-agenda][~org-agenda~]]
    - [[#agenda-files][Agenda files]]
    - [[#inbox-view-blocks][Inbox-view blocks]]
    - [[#agenda-views][Agenda views]]
    - [[#agenda-hook-to-add-status-text-to-all-project-blocks][Agenda hook to add status text to all project blocks]]
    - [[#general-agenda-settings][General agenda settings]]
      - [[#always-split-vertically-for-the-agenda][Always split vertically for the agenda]]
      - [[#remove-empty-blocks][Remove empty blocks]]
  - [[#org-capture-templates][~org-capture~ Templates]]
  - [[#processing-my-inbox][Processing my inbox]]
  - [[#project-management-any-task-with-subtasks-is-a-project][Project management: Any task with subtasks is a /project/!]]
  - [[#tracking-time-through-clocking][Tracking time through /clocking/]]
    - [[#general-clocking-settings][General clocking settings]]
    - [[#more-from-org-mode---organize-your-life-in-plain-text][More from Org Mode - Organize Your Life In Plain Text!]]
    - [[#define-hotkeys-for-clocking][Define hotkeys for clocking]]
  - [[#inactive-literate-programming-with-org-src-and-org-babel][INACTIVE Literate programming with ~org-src~ and ~org-babel~]]
  - [[#tracking-habits-with-org-habit][Tracking habits with ~org-habit~]]
  - [[#capture-directly-from-the-browser-with-org-protocol][Capture directly from the browser with ~org-protocol~]]
  - [[#inactive-my-paper-reading-workflow][INACTIVE My paper reading workflow]]
    - [[#general-variables][General Variables]]
  - [[#helm-bibtex][helm-bibtex]]
  - [[#better-screenshots-with-org-download][Better screenshots with ~org-download~]]
  - [[#org-latex-writing-workflow][Org latex writing workflow]]
    - [[#use-cleveref-in-latex][Use ~cleveref~ in LaTeX]]
    - [[#latex-exports][LaTeX exports]]
    - [[#cdlatex-environments][cdlatex environments]]
    - [[#syntax-highlight][Syntax highlight]]
    - [[#caption-below-tables-or-not][Caption below tables... or not!]]
    - [[#booktabs-for-tables][~booktabs~ for tables]]
    - [[#code-highlighting][Code highlighting]]
    - [[#no-hyperref-setup-by-default][No hyperref setup by default]]
    - [[#org-ref-hotkey][Org-ref hotkey]]
  - [[#zettelkasten-with-org-roam][/Zettelkasten/ with ~org-roam~]]
    - [[#set-directory][Set Directory]]
    - [[#autosync-mode-is-needed-apparently][Autosync Mode is needed apparently]]
    - [[#start-org-roam-mode-on-startup][Start ~org-roam-mode~ on startup]]
    - [[#add-hotkeys][Add hotkeys]]
    - [[#capture-template][Capture template]]
    - [[#capture-ref-from-browser][Capture Ref from Browser]]
    - [[#org-roam-bibtex][~org-roam-bibtex~]]
    - [[#org-roam-dailies][~org-roam dailies~]]
  - [[#drop-down-org-roam-dailies-via-yequake][Drop-down org-roam-dailies via ~yequake~]]
  - [[#org-hide-drawers][~org-hide-drawers~]]
- [[#other-packages--languages--concepts][Other Packages / Languages / Concepts]]
  - [[#manage-my-email-with-mu4e][Manage my Email with ~mu4e~]]
    - [[#contexts][Contexts]]
    - [[#send-emails][Send Emails]]
    - [[#notifications-for-new-email][Notifications for new Email]]
    - [[#custom-key-for-update-index][Custom key for update index]]
    - [[#custom-date-format][Custom date format]]
  - [[#writeroom][Writeroom]]
  - [[#make-windows-more-narrow-and-centered-for-more-aesthetics][Make windows more narrow and centered for more aesthetics]]
  - [[#magit---the-best-git-interface][~magit~ - The best git interface]]
    - [[#add-uni-tuebingen-gitlab][Add uni-tuebingen gitlab]]
  - [[#latex][LaTeX]]
    - [[#reftex][RefTex]]
    - [[#helm-bibtex-for-citations][Helm-bibtex for citations]]
    - [[#outline-minor-mode][Outline Minor Mode]]
    - [[#outline-magic][Outline-magic]]
    - [[#visual-fill-mode-instead-of-auto-fill][Visual fill mode instead of auto fill]]
    - [[#beamer-bold-as-bold-not-as-alert][Beamer: Bold as bold, not as alert!]]
  - [[#yasnippet][YASnippet]]
  - [[#budget-money-with-ledger-cli][Budget money with ~ledger-cli~]]
  - [[#grammar-checking-with-languagetool][Grammar checking with LanguageTool]]
  - [[#julia][Julia]]
    - [[#julia-block][Julia block]]
    - [[#add-jmd-to-markdown-mode][Add .jmd to markdown-mode]]
  - [[#bugfix-tramp][Bugfix TRAMP]]
  - [[#fira-code-ligatures][Fira Code Ligatures]]
  - [[#github-copilot][Github copilot]]
  - [[#firefox-as-default-browser][Firefox as default browser]]
  - [[#start-atomic-chrome-server-to-use-emacs-for-writing-in-a-browser][Start atomic-chrome server to use emacs for writing in a browser]]
  - [[#typst][typst]]
  - [[#agent-shell][~agent-shell~]]
    - [[#project-agent-shell-opener-with-helm][Project agent shell opener with helm]]
  - [[#vterm][~vterm~]]
    - [[#always-open-a-fresh-vterm-when-calling-vterm][Always open a fresh vterm when calling ~vterm~]]
    - [[#no-modeline][No modeline]]
    - [[#gruvbox-colors][Gruvbox colors]]
    - [[#font-fix][Font fix]]
  - [[#dirvish][~dirvish~]]

* General Emacs settings
Config also in [[file:init.el]]. All the layers are there, also all things that are
customized in the original config file.

** Hotkey to modify this config file.
#+BEGIN_SRC emacs-lisp
  (spacemacs/set-leader-keys "feC"
    (lambda() (interactive) (find-file "~/dotfiles/dotfiles/spacemacs.d/config.org")))
  (spacemacs/set-leader-keys "fed"
    (lambda() (interactive) (find-file "~/dotfiles/dotfiles/spacemacs.d/init.el")))
#+END_SRC

** I like visual line mode
#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook 'spacemacs/toggle-visual-line-navigation-on)
#+END_SRC

** Smoother undo behavior
#+BEGIN_SRC emacs-lisp
  (setq evil-want-fine-undo t)
#+END_SRC

** Better vertical splitting
#+BEGIN_SRC emacs-lisp
  (setq split-height-threshold nil)
  (setq split-width-threshold 100)
#+END_SRC
** Comment region/line with "C-S-c"
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-S-c") 'evilnc-comment-or-uncomment-lines)
#+END_SRC
** Larger scroll margin
#+BEGIN_SRC emacs-lisp
  (setq scroll-margin 1)
#+END_SRC

** PDFs
*** Fit PDF page to frame
open pdfs scaled to fit page
#+BEGIN_SRC emacs-lisp
  (setq-default pdf-view-display-size 'fit-page)
#+END_SRC

*** PDF: Dark mode to fit the gruvbox theme
midnight mode
#+begin_src emacs-lisp
  (setq pdf-view-midnight-colors '("#fdf4c1" . "#282828"))
#+end_src

Delete the border
#+begin_src emacs-lisp
  (add-hook 'pdf-view-mode-hook
            (lambda ()
              (set (make-local-variable
                    'evil-evilified-state-cursor)
                   (list nil))))
#+end_src

Always start in midnight mode
#+begin_src emacs-lisp
  ;; (add-hook 'pdf-tools-enabled-hook 'pdf-view-midnight-minor-mode)
#+end_src

** Auto-refresh buffers when files changed on disk
#+BEGIN_SRC emacs-lisp
  (global-auto-revert-mode t)
#+END_SRC

** ~libnotify~ to display notifications
#+BEGIN_SRC emacs-lisp
  (setq alert-default-style 'libnotify)
#+END_SRC

** Show time and date in modeline
#+begin_src emacs-lisp
  (setq display-time-day-and-date t)
#+end_src

** Pop-up shell
#+begin_src emacs-lisp
  ;; (setq shell-pop-universal-key "<f12>")
  (setq shell-default-shell 'eshell)
  (setq shell-pop-autocd-to-working-dir nil)
  (global-set-key (kbd "<f12>") 'spacemacs/default-pop-shell)
  (global-set-key (kbd "<s-f12>") 'spacemacs/default-pop-shell)
#+end_src

** Auth-info
#+begin_src emacs-lisp
  (setq auth-sources
        '((:source "~/.authinfo.gpg")))
#+end_src

** Nicer ~treemacs~
#+begin_src emacs-lisp
  (setq doom-themes-treemacs-theme
        ;; "doom-colors"
        "doom-atom"
        )
  (doom-themes-treemacs-config)
#+end_src

** Emacs-i3 window movement integration                                :WIP:
The goal here: Have one hotkey to move windows in both i3wm and Emacs.
The general idea had the following control flow:
- Check if the currently focused window is emacs
  - If not, change window focus as usual => DONW
  - If yes, pass key presses on to Emacs
    - Check if there is an emacs window on the desired direction
      - If yes, change window focus inside emacs => DONE
      - If not, change window focus in i3wm by calling ~i3-msg~ => DONE

First define my custom windmove functions
#+begin_src emacs-lisp
  (defun i3-windmove-left ()
    (interactive)
    (condition-case nil
        (windmove-left)
      (error (shell-command "i3-msg focus left"))))

  (defun i3-windmove-right ()
    (interactive)
    (condition-case nil
        (windmove-right)
      (error (shell-command "i3-msg focus right"))))

  (defun i3-windmove-up ()
    (interactive)
    (condition-case nil
        (windmove-up)
      (error (shell-command "i3-msg focus up"))))

  (defun i3-windmove-down ()
    (interactive)
    (condition-case nil
        (windmove-down)
      (error (shell-command "i3-msg focus down"))))
#+end_src

#+RESULTS:
: i3-windmove-down

Set custom hotkeys
#+begin_src emacs-lisp
  (global-set-key (kbd "C-s-h") 'i3-windmove-left)
  (global-set-key (kbd "C-s-j") 'i3-windmove-down)
  (global-set-key (kbd "C-s-k") 'i3-windmove-up)
  (global-set-key (kbd "C-s-l") 'i3-windmove-right)
#+end_src

#+RESULTS:
: i3-windmove-right

** Increase numbers with the same hotkeys as in vim
#+begin_src emacs-lisp
  (define-key evil-normal-state-map (kbd "C-a") 'evil-numbers/inc-at-pt)
  (define-key evil-visual-state-map (kbd "C-a") 'evil-numbers/inc-at-pt)
  (define-key evil-normal-state-map (kbd "C-x") 'evil-numbers/dec-at-pt)
  (define-key evil-visual-state-map (kbd "C-x") 'evil-numbers/dec-at-pt)
#+end_src

** Better eshell usage
Make `helm-eshell-history`, a.k.a. ", H", use the current frame instead of
opening a new one:
#+begin_src emacs-lisp
  (setq helm-show-completion-display-function #'helm-show-completion-default-display-function)
#+end_src

#+begin_src emacs-lisp
  (setq eshell-history-size 1000)
#+end_src

** Visible bell instead of ringing bell
#+begin_src emacs-lisp
  (setq visible-bell t)
#+end_src

** Do not start emacs with a warnings buffer open
#+begin_src emacs-lisp
  (setq display-buffer-alist
        '(("\\*Warnings\\*" (display-buffer-no-window))))
#+end_src

* Organize my life with ~org-mode~
I love org so much, it deserves its own heading.
** General settings
*** Prettier org
**** Inline images
#+BEGIN_SRC emacs-lisp
  ;; Inline images
  (setq org-startup-with-inline-images t)
  (setq org-image-actual-width (list 500))
#+END_SRC
**** Pretty entities
#+BEGIN_SRC emacs-lisp
  (setq org-pretty-entities t)
#+END_SRC
**** Hide emphasis markers, for increased prettiness
#+begin_src emacs-lisp
  (setq org-hide-emphasis-markers t)
#+end_src
**** Link Abbreviations
#+begin_src emacs-lisp
  (setq org-link-abbrev-alist
        '(
          ("wolfram" . "https://wolframalpha.com/input/?i=%s")
          ("duckduckgo" . "https://duckduckgo.com/?q=%s")
          ("gmap" . "https://maps.google.com/maps?q=%s")
          ("gimages" . "https://google.com/images?q=%s")
          ("google" . "https://google.com/search?q=")
          ("youtube" . "https://youtube.com/watch?v=%s")
          ("youtu" . "https://youtube.com/results?search_query=%s")
          ("github" . "https://github.com/%s")
          ))
#+end_src
*** Enforce todo dependencies
#+BEGIN_SRC emacs-lisp
  ;; Parents can only be marked as DONE if children tasks are undone
  ;; with the "ORDERED" property TODO children is blocked until all earlier siblings are marked DONE
  (setq org-enforce-todo-dependencies t)
#+END_SRC

*** Autosave org files
#+BEGIN_SRC emacs-lisp
  ;; Automatically save org buffers when agenda is open
  ;; (add-hook 'org-agenda-mode-hook
  ;;           (lambda ()
  ;;             (add-hook 'auto-save-hook 'org-save-all-org-buffers nil t)
  ;;             (auto-save-mode)))
  ;; Save even more stuff
  (add-hook 'auto-save-hook 'org-save-all-org-buffers)
#+END_SRC

*** Archive tag to gray out things I do not need
#+BEGIN_SRC emacs-lisp
  (setq org-archive-tag "inactive")
#+END_SRC

*** "project" tag: Do not inherit
#+BEGIN_SRC emacs-lisp
  (setq org-tags-exclude-from-inheritance '("project"))
#+END_SRC

*** Start org with some useful modes
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
  (add-hook 'org-mode-hook 'auto-fill-mode)
#+END_SRC

*** Column view
#+BEGIN_SRC emacs-lisp
  ;; (setq org-agenda-overriding-columns-format "%CATEGORY(Category) %3PRIORITY  %42ITEM(Details) %TAGS(Tags) %7TODO(To Do) %5Effort(Time){:} %7CLOCKSUM(Clocked){:}")
  (setq org-agenda-overriding-columns-format
        "%CATEGORY(Category) %1PRIORITY %7TODO(TODO) %58ITEM(Details) %5Effort(Time){:} %5CLOCKSUM(Clocked){:}")
#+END_SRC

*** Priorities
#+begin_src emacs-lisp
  (setq org-priority-lowest 68) ;; Add "D" for really unimportant stuff
  ;; (setq org-priority-highest 65) ;; Default
  (setq org-priority-default 67)
#+end_src
*** Make search work again
#+begin_src emacs-lisp
  (setq org-fold-core-style 'overlays)
  (evil-select-search-module 'evil-search-module 'evil-search)
#+end_src
*** Insert emojis
#+begin_src emacs-lisp
  (evil-leader/set-key-for-mode 'org-mode "i E" 'emoji-insert)
  ;; (unless (boundp 'counsel-find-file-map)
  ;; (defvar counsel-find-file-map (make-sparse-keymap)))
  ;; (evil-leader/set-key-for-mode 'org-mode "i E" 'ivy-emoji)
#+end_src
** ~org-refile~ targets
#+BEGIN_SRC emacs-lisp
  (setq org-refile-targets '(
                             ("~/org/inbox.org" :level . 0)
                             ("~/org/todo.org" :maxlevel . 2)
                             ("~/org/references.org" :level . 1)
                             ;; ("~/org/phd.org" :maxlevel . 2)
                             ("~/org/research.org" :maxlevel . 2)
                             ;; (nil . (:level . 1))
                             (nil . (:maxlevel . 2))
                             ))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq org-refile-use-outline-path 'file)
  (setq org-outline-path-complete-in-steps nil)
  (setq org-refile-allow-creating-parent-nodes 'confirm)
#+END_SRC
** Todo keywords
#+BEGIN_SRC emacs-lisp
  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(N)" "STARTED(s!)" "ONGOING(o)" "WAITING(W@/!)" "|" "INACTIVE(i)" "CANCELLED(c@)" "DONE(d!)")
          (sequence "TOREAD(r)" "|" "1PASS(1)" "2PASS(2)" "3PASS(3)")
          (sequence "TOWATCH(w)" "|")
          (sequence "TOLISTEN(l)" "|")
          (sequence "REMINDER(R)" "|")
          (sequence "|" "NOTE(n)" "REFERENCE(D)")
          ))
  (setq org-todo-keyword-faces
        '(
          ("TODO" . (:foreground "#fb4934" :weight bold))
          ("NEXT" . (:foreground "#d79921" :weight bold))
          ("TOREAD" . (:foreground "#d79921" :weight bold))
          ("TOWATCH" . (:foreground "#b16286" :weight bold))
          ("TOLISTEN" . (:foreground "#b16286" :weight bold))
          ("INACTIVE" . (:foreground "#a89984" :weight bold))
          ("WAITING" . (:foreground "#83a598" :weight bold))
          ("STARTED" . (:foreground "#fe8019" :weight bold))
          ("ONGOING" . (:foreground "#d79921" :weight bold))
          ("NOTE" . (:foreground "#458588" :weight bold))
          ("REFERENCE" . (:foreground "#458588" :weight bold))
          ("CANCELLED" . (:foreground "#928374" :weight bold))
          ("1PASS" . (:foreground "#98971a" :weight bold))
          ("2PASS" . (:foreground "#98971a" :weight bold))
          ("3PASS" . (:foreground "#98971a" :weight bold))
          ("REMINDER" . "#8ec07c")
          ))

  ;; Open the log-buffer in evil-insert-state
  (add-hook 'org-log-buffer-setup-hook 'evil-insert-state)
#+END_SRC

** TODO ~org-agenda~
*** Agenda files
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-files '("~/org/"
                           "~/org/cal/"
                           "~/org/projects/"
                           ;; "~/org/zettelkasten/"
                           ;; "~/org/zettelkasten/refs/"
                           "~/MEGA/papers/notes.org"
                           "~/org/zettelkasten/daily/"
                           ))
  (with-eval-after-load 'org (setq org-default-notes-file '"~/org/inbox.org"))
#+END_SRC
*** Inbox-view blocks
mu4e:
#+begin_src emacs-lisp
  (load "~/.spacemacs.d/mu4e-agenda-block.el")
#+end_src

whatsapp:
#+begin_src emacs-lisp
  (load "~/.spacemacs.d/whatsapp-agenda-block.el")
#+end_src

Signal:
#+begin_src emacs-lisp
  (load "~/.spacemacs.d/signal-agenda-block.el")
#+end_src

#+begin_src emacs-lisp
  (setq my/inbox-name-width 30)
  (setq my/inbox-preview-width 60)
  (setq my/inbox-date-format "%d/%m/%Y")
  (setq my/inbox-date-width 5)
#+end_src

*** Agenda views
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-custom-commands
        '(
          ("d" "Taskslist"
           ((tags-todo "-CATEGORY=\"papers\""
                       ((org-agenda-filter-preset '("-someday"))
                        (org-agenda-todo-ignore-scheduled 'future)
                        (org-agenda-tags-todo-honor-ignore-options t)))
            ))

          ;; GTD-like workflow; Currently unused, thus the hiding, but potentially very interesting!
          ("g" . "GTD")
          ("gc" "Upcoming week - Columns" agenda ""
           ((org-agenda-span 'week)
            (org-agenda-filter-preset '("-habit"))
            (org-agenda-view-columns-initially t)
            ))
          ("gn" "Next Actions"
           ((tags-todo "-CATEGORY=\"papers\""
                       ((org-agenda-filter-preset '("-someday"))
                        (org-agenda-todo-ignore-scheduled 'future)
                        (org-agenda-tags-todo-honor-ignore-options t)))
            ))
          ("gd" "Upcoming deadlines" agenda ""
           ((org-agenda-entry-types '(:deadline))
            (org-agenda-span 1)
            (org-deadline-warning-days 60)
            (org-agenda-overriding-header "Upcoming Deadlines")
            (org-agenda-time-grid nil)))

          ;; Special types
          ("r" "To read (excluding papers)"
           tags-todo "TODO=\"TOREAD\"-CATEGORY=\"papers\""
           (;;(org-agenda-filter-preset '(""))
            (org-agenda-sorting-strategy '(priority-down tag-down))))

          ("w" "Work"
           ((agenda ""
                    ((org-agenda-span 1)
                     (org-agenda-overriding-header "Thesis Agenda")))
            (tags-todo "CATEGORY=\"Research-Inbox\""
                       ((org-agenda-overriding-header "To Refile")))
            (tags-todo "-CANCELLED/!"
                       ((org-agenda-overriding-header "Stuck Projects")
                        (org-agenda-skip-function 'bh/skip-non-stuck-projects)
                        (org-agenda-sorting-strategy
                         '(category-keep))
                        (org-tags-match-list-sublevels 'indented)
                        (org-agenda-dim-blocked-tasks nil)))
            (tags-todo "-HOLD-CANCELLED/!"
                       ((org-agenda-overriding-header "Projects")
                        (org-agenda-skip-function 'bh/skip-non-projects)
                        ;; (org-tags-match-list-sublevels 'indented)
                        (org-agenda-sorting-strategy
                         '(category-keep))
                        (org-agenda-dim-blocked-tasks nil)))
            (tags-todo "Research-CANCELLED-WAITING-CATEGORY=\"papers\"-CATEGORY=\"Research-Inbox\""
                       ((org-agenda-overriding-header (concat "Standalone Tasks"
                                                              (if bh/hide-scheduled-and-waiting-next-tasks
                                                                  ""
                                                                " (including WAITING and SCHEDULED tasks)")))
                        (org-agenda-skip-function 'bh/skip-project-tasks)
                        (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks)
                        (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks)
                        (org-agenda-todo-ignore-with-date bh/hide-scheduled-and-waiting-next-tasks)

                        '(category-keep)))
            (tags-todo "-CANCELLED+WAITING|HOLD/!"
                       ((org-agenda-overriding-header (concat "Waiting and Postponed Tasks"
                                                              (if bh/hide-scheduled-and-waiting-next-tasks
                                                                  ""
                                                                " (including WAITING and SCHEDULED tasks)")))
                        (org-agenda-skip-function 'bh/skip-non-tasks)
                        (org-tags-match-list-sublevels nil)
                        (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks)
                        (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks)))
            (tags-todo "Research-CATEGORY=\"papers\""
                       ((org-agenda-todo-ignore-scheduled 'all)
                        (org-agenda-overriding-header "TODOs")))
            )
           ((org-agenda-filter-preset '("+Research")))
           )

          ("p" "Postdoc View"
           ((agenda "" ((org-agenda-span 1)))
            (tags "Research+project+focus"
                  ((org-agenda-overriding-header "Projects - focus")
                   (org-agenda-dim-blocked-tasks nil)))
            (tags "Research+project+active-focus"
                  ((org-agenda-overriding-header "Projects - active")
                   (org-agenda-dim-blocked-tasks nil)))
            (tags "Research+project-focus-active-inactive"
                       ((org-agenda-overriding-header "Projects - stack")
                        (org-agenda-dim-blocked-tasks nil)
                        ))
            (tags "Research+CATEGORY=\"Inbox\"+LEVEL=2"
                       ((org-agenda-overriding-header "To refile")))
            (tags-todo "Research+misc|organization-CANCELLED-WAITING-CATEGORY=\"papers\"-CATEGORY=\"Inbox\""
                       ((org-agenda-overriding-header "Non-project tasks")
                        (org-agenda-todo-ignore-scheduled 'all)
                        (org-agenda-tags-todo-honor-ignore-options t)
                        (org-agenda-todo-ignore-deadlines 'all)
                        (org-agenda-todo-ignore-with-date 'all)
                        (org-agenda-sorting-strategy '(priority-down))
                        ))
            (tags-todo "Research-project-inactive-CANCELLED-WAITING-CATEGORY=\"papers\"-CATEGORY=\"Inbox\""
                       ((org-agenda-overriding-header "All tasks")
                        (org-agenda-todo-ignore-scheduled 'all)
                        (org-agenda-tags-todo-honor-ignore-options t)
                        (org-agenda-todo-ignore-deadlines 'all)
                        (org-agenda-todo-ignore-with-date 'all)
                        (org-agenda-sorting-strategy '(priority-down))
                        ))
            )
           ((org-agenda-filter-preset '("+Research")))
           )
          ;; ("r" "Research View"
          ;;  ((agenda "" ((org-agenda-span 1)))
          ;;   (tags "Research+CATEGORY=\"Research-Inbox\"+LEVEL=2"
          ;;              ((org-agenda-overriding-header "To refile")))
          ;;   (tags-todo "Research+project"
          ;;              ((org-agenda-overriding-header "Active projects")
          ;;               (org-agenda-dim-blocked-tasks nil)
          ;;               ))
          ;;   (tags "Research+project+TODO=\"\""
          ;;              ((org-agenda-overriding-header "Stack / project ideas")
          ;;               (org-agenda-dim-blocked-tasks nil)
          ;;               ))
          ;;   (tags-todo "Research-project-CANCELLED-WAITING-CATEGORY=\"papers\"-CATEGORY=\"Inbox\""
          ;;              ((org-agenda-overriding-header "All tasks")
          ;;               (org-agenda-todo-ignore-scheduled 'all)
          ;;               (org-agenda-tags-todo-honor-ignore-options t)
          ;;               (org-agenda-todo-ignore-deadlines 'all)
          ;;               (org-agenda-todo-ignore-with-date 'all)
          ;;               (org-agenda-sorting-strategy '(priority-down))
          ;;               ))
          ;;   )
          ;;  )
          ("R" "Research Reading" tags-todo "Research+TODO=\"TOREAD\""
           ((org-agenda-todo-ignore-scheduled 'future)
            (org-agenda-sorting-strategy '(priority-down tag-down))
            (org-agenda-overriding-header "TOREAD (research.org)"))
           )


          ("a" "Standard View"
           ((agenda "" ((org-agenda-span 1)))
            (tags "Inbox"
                  ((org-agenda-overriding-header "To Refile")
                   (org-agenda-files '("~/org/inbox.org"))))
            (tags-todo "-Research-CATEGORY=\"papers\"-CATEGORY=\"Inbox\""
                       ((org-agenda-overriding-header "All Tasks")
                        (org-agenda-todo-ignore-scheduled 'all)
                        (org-agenda-tags-todo-honor-ignore-options t)
                        (org-agenda-todo-ignore-deadlines 'all)
                        (org-agenda-todo-ignore-with-date 'all)
                        (org-agenda-sorting-strategy '(priority-down))
                        ))
            )
           ((org-agenda-filter-preset '("-Research" "-inactive" "-ignore")))
           )

          ("A" "Agenda - Week view with all Tasks" agenda "" ((org-agenda-span 7)))

          ("c" "Cleanup" tags "-Research-papers+TODO=\"DONE\"|-Research-papers+TODO=\"CANCELLED\""
           ((org-agenda-skip-function 'bh/skip-project-tasks)))
          ("C" "Postdoc Cleanup" tags "Research-papers+TODO=\"DONE\"|Research-papers+TODO=\"CANCELLED\""
           ((org-agenda-skip-function 'bh/skip-project-tasks)))

          ("i" "Inboxes"
           (
            (my/org-agenda-mu4e-unread ""
             ((org-agenda-overriding-header "Unread emails")))
            (my/org-agenda-whatsapp-unread ""
             ((org-agenda-overriding-header "Unread WhatsApp")))
            (my/org-agenda-signal-unread ""
             ((org-agenda-overriding-header "Unread Signal")))
            (tags "Inbox"
                  ((org-agenda-overriding-header "inbox.org")
                   (org-agenda-files '("~/org/inbox.org"))))
            )
           ((org-agenda-filter-preset '("-Research" "-inactive" "-ignore")))
           )

          ))
#+END_SRC

*** Agenda hook to add status text to all project blocks
Generated with claude
#+begin_src emacs-lisp
  ;;; --- Define variables for customization ---

  (defvar my/agenda-entry-text-prefix
    "              > "
    "Prefix for body text lines (those starting with \"> \") in the agenda.")

  (defvar my/agenda-entry-next-prefix
    "              > "
    "Prefix for NEXT task lines in the agenda."
    )

    ;;; --- Customization ---

  (defvar my/agenda-entry-text-prefix "      "
    "Prefix for body text lines (those starting with \"> \") in the agenda.")

  (defvar my/agenda-entry-next-prefix "    > "
    "Prefix for NEXT task lines in the agenda.")

  (defvar my/agenda-entry-text-scan-lines 10
    "Number of body text lines to scan per entry.
    Only lines starting with \"> \" are kept after scanning.")

  (defvar my/agenda-entry-text-section-match "project"
    "Case-insensitive substring to match against section headers.
    All matching sections get body text and NEXT items.")

  (defvar my/agenda-entry-text-face nil
    "Face for body text lines in the agenda.
    Set to nil to use the default face.")

    ;;; --- Actual customization ---
  (setq my/agenda-entry-text-prefix "              ↪ ")
  ;; (setq my/agenda-entry-text-prefix "              ")
  (setq my/agenda-entry-next-prefix "              → ")
  (setq my/agenda-entry-text-face
        ;; nil ;; — normal text, no special face at all
        ;; 'shadow ;; grey, clearly de-emphasized
        'org-agenda-dimmed-todo-face ;; — org's built-in dimmed face, slightly less faded than shadow
        ;; 'font-lock-comment-face ;; — typically grey or muted, similar to shadow but theme-dependent
        ;; 'italic ;; — normal color but italicized. Distinguishes from headings without dimming
        )
#+end_src

#+begin_src emacs-lisp
  ;;; --- Implementation ---

  (defun my/org-agenda-get-next-items (marker)
    "Return a list of (title . marker) for NEXT items in the subtree at MARKER."
    (when (marker-buffer marker)
      (with-current-buffer (marker-buffer marker)
        (save-excursion
          (save-restriction
            (widen)
            (goto-char marker)
            (let ((subtree-end (save-excursion (org-end-of-subtree t) (point)))
                  items)
              (save-excursion
                (org-back-to-heading t)
                (outline-next-heading)
                (while (and (< (point) subtree-end) (not (eobp)))
                  (when (and (looking-at org-complex-heading-regexp)
                             (string= (match-string 2) "NEXT"))
                    (push (cons (org-get-heading t t t t)
                                (copy-marker (point-at-bol)))
                          items))
                  (outline-next-heading)))
              (nreverse items)))))))

  (defun my/org-agenda-add-entry-text-to-section (section-header n-lines)
    "Show body text and NEXT items below entries in the SECTION-HEADER section.
  N-LINES is the maximum number of body text lines to scan per entry.
  Only lines starting with \"> \" are displayed (prefix stripped).
  Uses `org-agenda-get-some-entry-text' internally, so drawers
  and planning lines are already excluded from the body text."
    (let ((inhibit-read-only t)
          (case-fold-search nil)
          insert-points)
      (save-excursion
        (goto-char (point-min))
        (when (search-forward section-header nil t)
          (forward-line 1)
          (let ((section-start (point))
                (section-end
                 (save-excursion
                   (catch 'found
                     (while (not (eobp))
                       (forward-line 1)
                       (let ((face (get-text-property (point) 'face)))
                         (when (if (listp face)
                                   (memq 'org-agenda-structure face)
                                 (eq face 'org-agenda-structure))
                           (throw 'found (point)))))
                     (point-max)))))
            ;; Collect (line-end-pos . marker) for each agenda entry in section
            (goto-char section-start)
            (while (< (point) section-end)
              (let ((marker (get-text-property (point) 'org-hd-marker)))
                (when marker
                  (push (cons (line-end-position) marker) insert-points)))
              (forward-line 1))
            ;; insert-points is bottom-to-top (due to push), which is the
            ;; order we need so that insertions don't shift earlier positions.
            (dolist (ip insert-points)
              (let* ((marker (cdr ip))
                     (body-txt (and (marker-buffer marker)
                                    (org-agenda-get-some-entry-text
                                     marker n-lines)))
                     (next-items (my/org-agenda-get-next-items marker))
                     (parts nil))
                ;; Build body text lines -- only lines starting with "> "
                (when (and body-txt (not (string= body-txt "")))
                  (dolist (l (split-string body-txt "\n" t))
                    (when (string-match-p "^> " l)
                      (let ((line (concat my/agenda-entry-text-prefix
                                          (substring l 2))))
                        (when my/agenda-entry-text-face
                          (add-face-text-property
                           0 (length line) my/agenda-entry-text-face nil line))
                        (push line parts)))))
                ;; Build NEXT item lines
                (dolist (item next-items)
                  (let* ((title (car item))
                         (m (cdr item))
                         (kw (propertize "NEXT"
                                         'face (org-get-todo-face "NEXT")))
                         (line (concat my/agenda-entry-next-prefix kw " " title)))
                    (add-text-properties 0 (length line)
                                         (list 'my/org-hd-marker m
                                               'todo-state "NEXT")
                                         line)
                    (push line parts)))
                (when parts
                  (goto-char (car ip))
                  (insert "\n"
                          (mapconcat #'identity (nreverse parts) "\n"))))))))))

  ;;; --- Hook ---

  (defun my/org-agenda-add-entry-text ()
    "Add body text and NEXT items to all project-related sections in the agenda."
    (save-excursion
      (goto-char (point-min))
      (while (not (eobp))
        (let ((face (get-text-property (point) 'face)))
          (when (and (if (listp face)
                         (memq 'org-agenda-structure face)
                       (eq face 'org-agenda-structure))
                     (let ((line (buffer-substring-no-properties
                                  (line-beginning-position)
                                  (line-end-position))))
                       (string-match-p my/agenda-entry-text-section-match
                                       (downcase line))))
            (let ((header (string-trim
                           (buffer-substring-no-properties
                            (line-beginning-position)
                            (line-end-position)))))
              (my/org-agenda-add-entry-text-to-section
               header my/agenda-entry-text-scan-lines))))
        (forward-line 1))))

  (add-hook 'org-agenda-finalize-hook #'my/org-agenda-add-entry-text)

  ;;; --- Make NEXT lines actionable ---

  (defun my/org-agenda-goto-at-point ()
    "If on a custom NEXT line, go to that heading. Otherwise defer to org."
    (interactive)
    (let ((marker (get-text-property (point) 'my/org-hd-marker)))
      (if (and marker (marker-buffer marker))
          (progn
            (switch-to-buffer-other-window (marker-buffer marker))
            (goto-char marker)
            (org-show-context)
            (org-show-entry))
        (org-agenda-goto))))

  (defun my/org-agenda-switch-to-at-point ()
    "If on a custom NEXT line, switch to that heading. Otherwise defer to org."
    (interactive)
    (let ((marker (get-text-property (point) 'my/org-hd-marker)))
      (if (and marker (marker-buffer marker))
          (progn
            (switch-to-buffer (marker-buffer marker))
            (goto-char marker)
            (org-show-context)
            (org-show-entry))
        (org-agenda-switch-to))))

  (defun my/org-agenda-todo-at-point ()
    "If on a custom NEXT line, toggle its TODO state. Otherwise defer to org."
    (interactive)
    (let ((marker (get-text-property (point) 'my/org-hd-marker)))
      (if (and marker (marker-buffer marker))
          (progn
            (org-with-point-at marker
              (org-todo))
            (when (eq major-mode 'org-agenda-mode)
              (org-agenda-redo)))
        (org-agenda-todo))))

  (with-eval-after-load 'org-agenda
    (define-key org-agenda-mode-map (kbd "TAB") #'my/org-agenda-goto-at-point)
    (define-key org-agenda-mode-map (kbd "<tab>") #'my/org-agenda-goto-at-point)
    (define-key org-agenda-mode-map (kbd "RET") #'my/org-agenda-switch-to-at-point)
    (define-key org-agenda-mode-map (kbd "<return>") #'my/org-agenda-switch-to-at-point)
    (define-key org-agenda-mode-map (kbd "t") #'my/org-agenda-todo-at-point))
#+end_src

*** General agenda settings
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-tags-todo-honor-ignore-options t)
  (setq org-agenda-filter-preset '("-ignore")) ;; probably not doing anything?
  (setq org-log-into-drawer t)
  (setq org-agenda-log-mode-items '(clock state))

  (setq org-agenda-skip-deadline-if-done t)
  (setq org-agenda-skip-scheduled-if-done t)

  ;; Start agenda in day mode
  (setq org-agenda-span 7)

  ;; Start week on monday
  (setq org-agenda-start-on-weekday 1)

  ;; Tasks that cannot be done because of dependencies should not clutter the agenda
  ;; t grays them out, 'invisible makes them disappear
  (setq org-agenda-dim-blocked-tasks t)

  ;; Better overview in agenda with my recurring tasks
  (setq org-agenda-show-future-repeats 'next)

  ;; Include archived files
  (setq org-agenda-archives-mode t)

  ;; Re-center after jumping to an agenda item
  (add-hook 'org-agenda-after-show-hook #'recenter)

  ;; Hide some not-that-informative tags from the agenda view
  (setq org-agenda-hide-tags-regexp "Research\\|project\\|active\\|idea")
#+END_SRC

**** Always split vertically for the agenda
#+begin_src emacs-lisp
  (add-to-list 'display-buffer-alist
             '("\\*Org Agenda\\*"
               (display-buffer-in-direction)
               (direction . right)
               (window-width . 0.5)))
#+end_src

**** Remove empty blocks
#+begin_src emacs-lisp
  (defun my/remove-empty-agenda-blocks ()
    "Remove agenda block headers (with separator) that have no entries."
    (save-excursion
      (goto-char (point-min))
      (let ((inhibit-read-only t))
        (while (re-search-forward
                ;; "^─+\n\\([^\n─].*\n\\)\n*\\(─\\)" nil t)
                "^=+\n\\([^\n─].*\n\\)\n*\\(=\\)" nil t)
          (replace-match "\\2")))))

  (add-hook 'org-agenda-finalize-hook #'my/remove-empty-agenda-blocks)
#+end_src

** TODO [#D] ~org-capture~ Templates
#+BEGIN_SRC emacs-lisp
  (setq org-capture-templates
        '(
          ("t" "Todo" entry (file "~/org/inbox.org")
           "* TODO %?\n%U"
           ;; :clock-in t :clock-resume t
           )
          ("T" "Todo Today" entry (file "~/org/inbox.org")
           "* TODO %?\nSCHEDULED: %t\n%U\n" :empty-lines 1
           ;; :clock-in t :clock-resume t
           )
          ("n" "Note" entry (file "~/org/inbox.org")
           "* NOTE %?\n%U" :empty-lines 1
           ;; :clock-in t :clock-resume t
           )
          ("N" "Note with Clipboard" entry (file "~/org/inbox.org")
           "* NOTE %?\n%U\n%c\n" :empty-lines 1)
          ;; Default free-form journal entry. I typically only use this
          ;; to create the heading and then edit the journal.org file
          ;; directly myself.
          ("j" "Journal" entry (file+olp+datetree "~/org/journal.org")
           "* %?\n\nEntered on %U\n  %i"
           ;; :clock-in t :clock-resume t
           )
          ;; Daily journaling
          ;; This one is quite inactive rn [2026-02-26 Thu]
          ("J" "Daily journal" entry (file+olp+datetree "~/org/journal.org")
           "* %?
  _Zum Vortag:_


  _Dafür bin ich dankbar:_


  _Darauf bin ich stolz:_


  _Das habe ich gelernt:_


  _Top-3 Energy Givers:_
  1.
  2.
  3.

  _Top-3 Energy Thieves:_
  1.
  2.
  3.

  _Top-3 todos for today:_
  1.
  2.
  3.

  _Darauf bin ich heute neugierig:_

  "
           ;; :clock-in t :clock-resume t
           )

          ;; Add Emails as tasks to my default inbox
          ("e" "Email" entry (file "~/org/inbox.org")
           "* TODO Email: %a (%:fromname) \n:PROPERTIES:\n:CREATED: %U\n:EMAIL-SOURCE: %l\n:END:\n%U\n"
           ;; :clock-in t :clock-resume t
           )
          ))
#+END_SRC

Postdoc-related captures:
#+begin_src emacs-lisp
  (setq org-capture-templates
        (append
         org-capture-templates
         '(("p" "Postdoc")
           ("pt" "Task" entry
            (file+headline "~/org/research.org" "Inbox")
            "** TODO %?\n%U"
            ;; :clock-in t :clock-resume t
            )
           ("pT" "Task (Today)" entry (file+headline "~/org/research.org" "Inbox")
            "** TODO %?\nSCHEDULED: %t\n%U\n"
            ;; :clock-in t :clock-resume t
            )
           ("pn" "Note" entry (file+headline "~/org/research.org" "Inbox")
            "** NOTE %?\n%U"
            ;; :clock-in t :clock-resume t
            )
           ;; Postdoc journal is currently inactive
           ;; ("pj" "Journal" entry (file+olp+datetree "~/org/research_journal.org")
           ;;  "* %?\n\nEntered on %U\n%i" :clock-in t :clock-resume t)
           ("pd" "Daily brainstorm" entry
            (file+headline "~/org/research.org" "Daily brainstorm")
            ;; "* %\n*Did:* %^{Did}\n*Struggle:* %^{Struggle}\n*Today:* %^{Today}"
            "* %t\n- [ ] %?"
            ;; :clock-in t :clock-resume t
            :jump-to-captured t
            )
           ("pe" "Email" entry (file+headline "~/org/research.org" "Inbox")
            "* TODO Email: %a (%:fromname) \n:PROPERTIES:\n:CREATED: %U\n:EMAIL-SOURCE: %l\n:END:\n%U\n"
            ;; :clock-in t :clock-resume t
            )
           )
         ))
#+end_src
** TODO Processing my inbox
Curtesy of Jethro Kuan: https://github.com/jethrokuan/dots/blob/master/.doom.d/config.el
#+begin_src emacs-lisp
  (defun jethro/org-process-inbox ()
  "Called in org-agenda-mode, processes all inbox items."
  (interactive)
  (org-agenda-bulk-mark-regexp "inbox:")
  (jethro/bulk-process-entries))

  (defun jethro/org-agenda-process-inbox-item ()
    "Process a single item in the org-agenda."
    (org-with-wide-buffer
     (org-agenda-set-tags)
     (org-agenda-priority)
     ;; (call-interactively 'jethro/my-org-agenda-set-effort)
     (org-agenda-refile nil nil t)))

  (defun jethro/bulk-process-entries ()
  (if (not (null org-agenda-bulk-marked-entries))
      (let ((entries (reverse org-agenda-bulk-marked-entries))
            (processed 0)
            (skipped 0))
        (dolist (e entries)
          (let ((pos (text-property-any (point-min) (point-max) 'org-hd-marker e)))
            (if (not pos)
                (progn (message "Skipping removed entry at %s" e)
                       (cl-incf skipped))
              (goto-char pos)
              (let (org-loop-over-headlines-in-active-region) (funcall 'jethro/org-agenda-process-inbox-item))
              ;; `post-command-hook' is not run yet.  We make sure any
              ;; pending log note is processed.
              (when (or (memq 'org-add-log-note (default-value 'post-command-hook))
                        (memq 'org-add-log-note post-command-hook))
                (org-add-log-note))
              (cl-incf processed))))
        (org-agenda-redo)
        (unless org-agenda-persistent-marks (org-agenda-bulk-unmark-all))
        (message "Acted on %d entries%s%s"
                 processed
                 (if (= skipped 0)
                     ""
                   (format ", skipped %d (disappeared before their turn)"
                           skipped))
                 (if (not org-agenda-persistent-marks) "" " (kept marked)")))))

  ;; (defun jethro/my-org-agenda-set-effort (effort)
  ;;   "Set the effort property for the current headline."
  ;;   (interactive
  ;;    (list (read-string (format "Effort [%s]: " jethro/org-current-effort) nil nil jethro/org-current-effort)))
  ;;   (setq jethro/org-current-effort effort)
  ;;   (org-agenda-check-no-diary)
  ;;   (let* ((hdmarker (or (org-get-at-bol 'org-hd-marker)
  ;;                        (org-agenda-error)))
  ;;          (buffer (marker-buffer hdmarker))
  ;;          (pos (marker-position hdmarker))
  ;;          (inhibit-read-only t)
  ;;          newhead)
  ;;     (org-with-remote-undo buffer
  ;;       (with-current-buffer buffer
  ;;         (widen)
  ;;         (goto-char pos)
  ;;         (org-show-context 'agenda)
  ;;         (funcall-interactively 'org-set-effort nil jethro/org-current-effort)
  ;;         (end-of-line 1)
  ;;         (setq newhead (org-get-heading)))
  ;;       (org-agenda-change-all-lines newhead hdmarker))))

  ;; (map-put! org-agenda-keymap
  ;;           "P" #'jethro/org-process-inbox-item)
  ;; (evil-leader/set-key-for-mode 'org-agenda-mode "P" 'jethro/org-process-inbox-item)
  (evil-leader/set-key-for-mode 'org-agenda-mode "P" 'jethro/org-process-inbox)
#+end_src

** TODO Project management: Any task with subtasks is a /project/!
Copied from [[http://doc.norang.ca/org-mode.html#Projects][Org Mode - Organize Your Life In Plain Text!]]
#+begin_src emacs-lisp
  (setq org-stuck-projects (quote ("" nil nil "")))

  (defun bh/is-project-p ()
    "Any task with a todo keyword subtask"
    (save-restriction
      (widen)
      (let ((has-subtask)
            (subtree-end (save-excursion (org-end-of-subtree t)))
            (is-a-task (member (nth 2 (org-heading-components)) org-todo-keywords-1)))
        (save-excursion
          (forward-line 1)
          (while (and (not has-subtask)
                      (< (point) subtree-end)
                      (re-search-forward "^\*+ " subtree-end t))
            (when (member (org-get-todo-state) org-todo-keywords-1)
              (setq has-subtask t))))
        (and is-a-task has-subtask))))

  (defun bh/is-project-subtree-p ()
    "Any task with a todo keyword that is in a project subtree.
  Callers of this function already widen the buffer view."
    (let ((task (save-excursion (org-back-to-heading 'invisible-ok)
                                (point))))
      (save-excursion
        (bh/find-project-task)
        (if (equal (point) task)
            nil
          t))))

  (defun bh/is-task-p ()
    "Any task with a todo keyword and no subtask"
    (save-restriction
      (widen)
      (let ((has-subtask)
            (subtree-end (save-excursion (org-end-of-subtree t)))
            (is-a-task (member (nth 2 (org-heading-components)) org-todo-keywords-1)))
        (save-excursion
          (forward-line 1)
          (while (and (not has-subtask)
                      (< (point) subtree-end)
                      (re-search-forward "^\*+ " subtree-end t))
            (when (member (org-get-todo-state) org-todo-keywords-1)
              (setq has-subtask t))))
        (and is-a-task (not has-subtask)))))

  (defun bh/is-subproject-p ()
    "Any task which is a subtask of another project"
    (let ((is-subproject)
          (is-a-task (member (nth 2 (org-heading-components)) org-todo-keywords-1)))
      (save-excursion
        (while (and (not is-subproject) (org-up-heading-safe))
          (when (member (nth 2 (org-heading-components)) org-todo-keywords-1)
            (setq is-subproject t))))
      (and is-a-task is-subproject)))

  (defun bh/list-sublevels-for-projects-indented ()
    "Set org-tags-match-list-sublevels so when restricted to a subtree we list all subtasks.
    This is normally used by skipping functions where this variable is already local to the agenda."
    (if (marker-buffer org-agenda-restrict-begin)
        (setq org-tags-match-list-sublevels 'indented)
      (setq org-tags-match-list-sublevels nil))
    nil)

  (defun bh/list-sublevels-for-projects ()
    "Set org-tags-match-list-sublevels so when restricted to a subtree we list all subtasks.
    This is normally used by skipping functions where this variable is already local to the agenda."
    (if (marker-buffer org-agenda-restrict-begin)
        (setq org-tags-match-list-sublevels t)
      (setq org-tags-match-list-sublevels nil))
    nil)

  (defvar bh/hide-scheduled-and-waiting-next-tasks t)

  (defun bh/toggle-next-task-display ()
    (interactive)
    (setq bh/hide-scheduled-and-waiting-next-tasks (not bh/hide-scheduled-and-waiting-next-tasks))
    (when  (equal major-mode 'org-agenda-mode)
      (org-agenda-redo))
    (message "%s WAITING and SCHEDULED NEXT Tasks" (if bh/hide-scheduled-and-waiting-next-tasks "Hide" "Show")))

  (defun bh/skip-stuck-projects ()
    "Skip trees that are not stuck projects"
    (save-restriction
      (widen)
      (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
        (if (bh/is-project-p)
            (let* ((subtree-end (save-excursion (org-end-of-subtree t)))
                   (has-next ))
              (save-excursion
                (forward-line 1)
                (while (and (not has-next) (< (point) subtree-end) (re-search-forward "^\\*+ NEXT " subtree-end t))
                  (unless (member "WAITING" (org-get-tags-at))
                    (setq has-next t))))
              (if has-next
                  nil
                next-headline)) ; a stuck project, has subtasks but no next task
          nil))))

  (defun bh/skip-non-stuck-projects ()
    "Skip trees that are not stuck projects"
    ;; (bh/list-sublevels-for-projects-indented)
    (save-restriction
      (widen)
      (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
        (if (bh/is-project-p)
            (let* ((subtree-end (save-excursion (org-end-of-subtree t)))
                   (has-next ))
              (save-excursion
                (forward-line 1)
                (while (and (not has-next) (< (point) subtree-end) (re-search-forward "^\\*+ NEXT " subtree-end t))
                  (unless (member "WAITING" (org-get-tags-at))
                    (setq has-next t))))
              (if has-next
                  next-headline
                nil)) ; a stuck project, has subtasks but no next task
          next-headline))))

  (defun bh/skip-non-projects ()
    "Skip trees that are not projects"
    ;; (bh/list-sublevels-for-projects-indented)
    (if (save-excursion (bh/skip-non-stuck-projects))
        (save-restriction
          (widen)
          (let ((subtree-end (save-excursion (org-end-of-subtree t))))
            (cond
             ((bh/is-project-p)
              nil)
             ((and (bh/is-project-subtree-p) (not (bh/is-task-p)))
              nil)
             (t
              subtree-end))))
      (save-excursion (org-end-of-subtree t))))

  (defun bh/skip-non-tasks ()
    "Show non-project tasks.
  Skip project and sub-project tasks, habits, and project related tasks."
    (save-restriction
      (widen)
      (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
        (cond
         ((bh/is-task-p)
          nil)
         (t
          next-headline)))))

  (defun bh/skip-project-trees-and-habits ()
    "Skip trees that are projects"
    (save-restriction
      (widen)
      (let ((subtree-end (save-excursion (org-end-of-subtree t))))
        (cond
         ((bh/is-project-p)
          subtree-end)
         ((org-is-habit-p)
          subtree-end)
         (t
          nil)))))

  (defun bh/skip-projects-and-habits-and-single-tasks ()
    "Skip trees that are projects, tasks that are habits, single non-project tasks"
    (save-restriction
      (widen)
      (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
        (cond
         ((org-is-habit-p)
          next-headline)
         ((and bh/hide-scheduled-and-waiting-next-tasks
               (member "WAITING" (org-get-tags-at)))
          next-headline)
         ((bh/is-project-p)
          next-headline)
         ((and (bh/is-task-p) (not (bh/is-project-subtree-p)))
          next-headline)
         (t
          nil)))))

  (defun bh/skip-project-tasks-maybe ()
    "Show tasks related to the current restriction.
  When restricted to a project, skip project and sub project tasks, habits, NEXT tasks, and loose tasks.
  When not restricted, skip project and sub-project tasks, habits, and project related tasks."
    (save-restriction
      (widen)
      (let* ((subtree-end (save-excursion (org-end-of-subtree t)))
             (next-headline (save-excursion (or (outline-next-heading) (point-max))))
             (limit-to-project (marker-buffer org-agenda-restrict-begin)))
        (cond
         ((bh/is-project-p)
          next-headline)
         ((org-is-habit-p)
          subtree-end)
         ((and (not limit-to-project)
               (bh/is-project-subtree-p))
          subtree-end)
         ((and limit-to-project
               (bh/is-project-subtree-p)
               (member (org-get-todo-state) (list "NEXT")))
          subtree-end)
         (t
          nil)))))

  (defun bh/skip-project-tasks ()
    "Show non-project tasks.
  Skip project and sub-project tasks, habits, and project related tasks."
    (save-restriction
      (widen)
      (let* ((subtree-end (save-excursion (org-end-of-subtree t))))
        (cond
         ((bh/is-project-p)
          subtree-end)
         ((org-is-habit-p)
          subtree-end)
         ((bh/is-project-subtree-p)
          subtree-end)
         (t
          nil)))))

  (defun bh/skip-non-project-tasks ()
    "Show project tasks.
  Skip project and sub-project tasks, habits, and loose non-project tasks."
    (save-restriction
      (widen)
      (let* ((subtree-end (save-excursion (org-end-of-subtree t)))
             (next-headline (save-excursion (or (outline-next-heading) (point-max)))))
        (cond
         ((bh/is-project-p)
          next-headline)
         ((org-is-habit-p)
          subtree-end)
         ((and (bh/is-project-subtree-p)
               (member (org-get-todo-state) (list "NEXT")))
          subtree-end)
         ((not (bh/is-project-subtree-p))
          subtree-end)
         (t
          nil)))))

  (defun bh/skip-projects-and-habits ()
    "Skip trees that are projects and tasks that are habits"
    (save-restriction
      (widen)
      (let ((subtree-end (save-excursion (org-end-of-subtree t))))
        (cond
         ((bh/is-project-p)
          subtree-end)
         ((org-is-habit-p)
          subtree-end)
         (t
          nil)))))

  (defun bh/skip-non-subprojects ()
    "Skip trees that are not projects"
    (let ((next-headline (save-excursion (outline-next-heading))))
      (if (bh/is-subproject-p)
          nil
        next-headline)))
#+end_src

** TODO Tracking time through /clocking/
*** General clocking settings
#+BEGIN_SRC emacs-lisp
  (setq org-clock-out-when-done t)
  (setq org-clock-out-remove-zero-time-clocks t)
  (setq org-clock-report-include-clocking-task t)
  (setq org-duration-format 'h:mm)

  ;; Agenda clock report parameters
  (setq org-agenda-clockreport-parameter-plist '(:link t :maxlevel 4 :fileskip0 t :compact t))

  ;; This seems to lead to some unpleasant behavior
  ;; (add-hook 'kill-emacs-hook #'org-clock-out)

  (spacemacs/toggle-mode-line-org-clock-on)
#+END_SRC

*** More from [[http://doc.norang.ca/org-mode.html#ClockSetup][Org Mode - Organize Your Life In Plain Text!]]
#+begin_src emacs-lisp
  ;; Resume clocking task when emacs is restarted
  (org-clock-persistence-insinuate)
  ;; Save the running clock and all clock history when exiting Emacs, load it on startup
  (setq org-clock-persist t)

  ;; Show lot of clocking history so it's easy to pick items off the C-F11 list
  (setq org-clock-history-length 23)
  ;; Resume clocking task on clock-in if the clock is open
  (setq org-clock-in-resume t)
  ;; Save clock data and state changes and notes in the LOGBOOK drawer
  (setq org-clock-into-drawer t)
#+end_src

Now the fun part: Clock into parent if it has some TODO keyword; Into the
default task otherwise
#+begin_src emacs-lisp
  (setq bh/keep-clock-running nil)

  (defun bh/clock-in-to-next (kw)
    "Switch a task from TODO to NEXT when clocking in.
  Skips capture tasks, projects, and subprojects.
  Switch projects and subprojects from NEXT back to TODO"
    (when (not (and (boundp 'org-capture-mode) org-capture-mode))
      (cond
       ((and (member (org-get-todo-state) (list "TODO"))
             (bh/is-task-p))
        "NEXT")
       ((and (member (org-get-todo-state) (list "NEXT"))
             (bh/is-project-p))
        "TODO"))))

  (defun bh/find-project-task ()
    "Move point to the parent (project) task if any"
    (save-restriction
      (widen)
      (let ((parent-task (save-excursion (org-back-to-heading 'invisible-ok) (point))))
        (while (org-up-heading-safe)
          (when (member (nth 2 (org-heading-components)) org-todo-keywords-1)
            (setq parent-task (point))))
        (goto-char parent-task)
        parent-task)))

  (defun bh/punch-in (arg)
    "Start continuous clocking and set the default task to the
  selected task.  If no task is selected set the Organization task
  as the default task."
    (interactive "p")
    (setq bh/keep-clock-running t)
    (if (equal major-mode 'org-agenda-mode)
        ;;
        ;; We're in the agenda
        ;;
        (let* ((marker (org-get-at-bol 'org-hd-marker))
               (tags (org-with-point-at marker (org-get-tags-at))))
          (if (and (eq arg 4) tags)
              (org-agenda-clock-in '(16))
            (bh/clock-in-organization-task-as-default)))
      ;;
      ;; We are not in the agenda
      ;;
      (save-restriction
        (widen)
        ; Find the tags on the current task
        (if (and (equal major-mode 'org-mode) (not (org-before-first-heading-p)) (eq arg 4))
            (org-clock-in '(16))
          (bh/clock-in-organization-task-as-default)))))

  (defun bh/punch-out ()
    (interactive)
    (setq bh/keep-clock-running nil)
    (when (org-clock-is-active)
      (org-clock-out))
    (org-agenda-remove-restriction-lock))

  (defun bh/clock-in-default-task ()
    (save-excursion
      (org-with-point-at org-clock-default-task
        (org-clock-in))))

  (defun bh/clock-in-parent-task ()
    "Move point to the parent (project) task if any and clock in"
    (let ((parent-task))
      (save-excursion
        (save-restriction
          (widen)
          (while (and (not parent-task) (org-up-heading-safe))
            (when (member (nth 2 (org-heading-components)) org-todo-keywords-1)
              (setq parent-task (point))))
          (if parent-task
              (org-with-point-at parent-task
                (org-clock-in))
            (when bh/keep-clock-running
              (bh/clock-in-default-task)))))))

  (defvar bh/organization-task-id "7ba25ac9-bd88-49a0-b9d2-59f9d4ccadf5")

  (defun bh/clock-in-organization-task-as-default ()
    (interactive)
    (org-with-point-at (org-id-find bh/organization-task-id 'marker)
      (org-clock-in '(16))))

  (defvar bh/break-task-id "390880c4-2101-48c3-ac36-c511a12b8ccd")

  (defun bh/clock-in-break ()
    (interactive)
    (org-with-point-at (org-id-find bh/break-task-id 'marker)
      (org-clock-in)))

  (defvar bh/lesemittwoch-task-id "3013a796-8804-4ddd-841c-e127ad95be15")

  (defun bh/clock-in-lesemittwoch ()
    (interactive)
    (org-with-point-at (org-id-find bh/lesemittwoch-task-id 'marker)
      (org-clock-in)))

  (defvar bh/mail-task-id "d717e2d0-53ec-4301-ae25-c8669cf855ce")

  (defun bh/clock-in-mail ()
    (interactive)
    (org-with-point-at (org-id-find bh/mail-task-id 'marker)
      (org-clock-in)))

  (defvar bh/distraction-task-id "956883ae-9af4-4a7c-a7a6-996fc10b76a8")

  (defun bh/clock-in-distraction ()
    (interactive)
    (org-with-point-at (org-id-find bh/distraction-task-id 'marker)
      (org-clock-in)))

  (defun bh/clock-out-maybe ()
    (when (and bh/keep-clock-running
               (not org-clock-clocking-in)
               (marker-buffer org-clock-default-task)
               (not org-clock-resolving-clocks-due-to-idleness))
      (bh/clock-in-parent-task)))

  (add-hook 'org-clock-out-hook 'bh/clock-out-maybe 'append)
#+end_src
*** Define hotkeys for clocking
#+begin_src emacs-lisp
  (evil-leader/set-key-for-mode 'org-mode "C s" 'bh/punch-in)
  (evil-leader/set-key "a o C s" 'bh/punch-in)
  (evil-leader/set-key-for-mode 'org-mode "C S" 'bh/punch-out)
  (evil-leader/set-key "a o C S" 'bh/punch-out)
  (evil-leader/set-key-for-mode 'org-mode "C b" 'bh/clock-in-break)
  (evil-leader/set-key "a o C b" 'bh/clock-in-break)
  (evil-leader/set-key-for-mode 'org-mode "C l" 'bh/clock-in-lesemittwoch)
  (evil-leader/set-key "a o C l" 'bh/clock-in-lesemittwoch)
  (evil-leader/set-key-for-mode 'org-mode "C m" 'bh/clock-in-mail)
  (evil-leader/set-key "a o C m" 'bh/clock-in-mail)
  (evil-leader/set-key-for-mode 'org-mode "C D" 'bh/clock-in-distraction)
  (evil-leader/set-key "a o C D" 'bh/clock-in-distraction)
#+end_src
** INACTIVE Literate programming with ~org-src~ and ~org-babel~
CLOSED: [2026-02-26 Thu 11:36]
NOTE [2026-02-26 Thu]: I think I'm not using this much anymore

Org-babel languages
#+BEGIN_SRC emacs-lisp
  (setq  inferior-julia-program-name (executable-find "julia"))

  (org-babel-do-load-languages
   'org-babel-load-languages
   '((C . t)
     (python . t)
     (gnuplot . t)
     (shell . t)
     ;; (jupyter . t)
     (julia . t)
     (ledger . t)
     ))
#+END_SRC

Correct indentation in org-babel source blocks
#+BEGIN_SRC emacs-lisp
  (setq org-src-tab-acts-natively t)
#+END_SRC

Evaluate without confirmation
#+BEGIN_SRC emacs-lisp
  (setq org-confirm-babel-evaluate nil)
#+END_SRC
** Tracking habits with ~org-habit~
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-modules 'org-habit)
  (setq org-habit-graph-column 50)
#+END_SRC

** Capture directly from the browser with ~org-protocol~
#+begin_src emacs-lisp
  (add-to-list 'org-modules 'org-protocol)
#+end_src

Capture template
#+begin_src emacs-lisp
  (setq org-capture-templates
        (append
         org-capture-templates
         '(("y" "org-protocol-capture" entry (file "~/org/inbox.org")
            "* TODO [[%:link][%:description]]\n%U\n %i" :immediate-finish t)
           )
         ))
#+end_src

** INACTIVE My paper reading workflow
CLOSED: [2026-02-26 Thu 11:36]
*This might not be up to date anymore, since I'm using org-roam now!*

Sources:
- https://github.com/jkitchin/org-ref

*** General Variables
Basically three parts:
- global bibliography file
- my notes
- pdf directory
These have to be defined in multiple locations as I use multiple different
libraries for this task
#+BEGIN_SRC emacs-lisp
  (setq reftex-default-bibliography '("~/MEGA/papers/references.bib"))

  ;; see org-ref for use of these variables
  (setq org-ref-bibliography-notes "~/MEGA/papers/notes.org"
        org-ref-default-bibliography '("~/MEGA/papers/references.bib")
        org-ref-pdf-directory "~/MEGA/papers/lib/")

  (setq helm-bibtex-notes-path "~/MEGA/papers/notes.org"
        helm-bibtex-bibliography "~/MEGA/papers/references.bib"
        helm-bibtex-library-path "~/MEGA/papers/lib/")

  ;; Further variables for helm-bibtex
  (setq bibtex-completion-bibliography "~/MEGA/papers/references.bib"
        bibtex-completion-library-path "~/MEGA/papers/lib/"
        bibtex-completion-notes-path "~/MEGA/papers/notes.org")

  ;; Download directory
  (setq biblio-download-directory "~/MEGA/papers/lib")
#+END_SRC
** helm-bibtex
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key-for-mode 'bibtex-mode "B" 'helm-bibtex)
#+END_SRC
** Better screenshots with ~org-download~
#+BEGIN_SRC emacs-lisp
  ;; Not optimal, but otherwise it creates wayy too many folders
  (setq-default org-download-image-dir "~/org/images")
  (setq org-download-screenshot-method "sleep 1; scrot -s %s")
  (setq org-download-image-latex-width 7)
#+END_SRC
** Org latex writing workflow
For when I write org to not write LaTeX
*** Use ~cleveref~ in LaTeX
#+begin_src emacs-lisp
  (setq org-ref-default-ref-type "cref")
  (setq org-latex-prefer-user-labels t)
#+end_src
*** LaTeX exports
#+BEGIN_SRC emacs-lisp
  ;; (setq org-latex-pdf-process (list "latexmk -pdf %f"))
  (setq org-latex-pdf-process (list
                               "latexmk -pdflatex='lualatex -shell-escape -interaction nonstopmode' -pdf -f  %f"))

  (add-to-list 'org-latex-classes
               '("letter" "\\documentclass{letter}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
  (add-to-list 'org-latex-classes
               '("article" "\\documentclass[a4paper]{article}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
  (add-to-list 'org-latex-classes
               '("scrbook" "\\documentclass{scrbook}"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
  (add-to-list 'org-latex-classes
               '("tumthesis" "\\documentclass{tumthesis}"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
  (add-to-list 'org-latex-classes
               '("mimosis" "\\documentclass{mimosis}"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))

  (evil-leader/set-key-for-mode 'org-mode "e p"
    'org-latex-export-to-pdf)
  ;; (lambda () (interactive) (org-latex-export-to-pdf t)))
  (evil-leader/set-key-for-mode 'org-mode "e B"
    'org-beamer-export-to-pdf)
  (evil-leader/set-key-for-mode 'org-mode "e b"
    'org-beamer-export-to-latex)
  ;; (lambda () (interactive) (org-beamer-export-to-pdf t)))
  (evil-leader/set-key-for-mode 'org-mode "e t"
    'org-latex-export-to-latex)
#+END_SRC

Ability to ignore headings in the export, so that I can use them just to
structure and fold my text:
#+begin_src emacs-lisp
  (require 'ox-extra)
  (ox-extras-activate '(ignore-headlines org-export-ignore-headlines))
#+end_src

Make TODOs red in the latex export
#+begin_src emacs-lisp
(defun org-latex-format-headline-colored-keywords-function
    (todo todo-type priority text tags info)
        (concat
           (cond ((string= todo "TODO")(and todo (format "{\\color{red}\\bfseries\\sffamily %s} " todo)))
   ((string= todo "DONE")(and todo (format "{\\color{green}\\bfseries\\sffamily %s} " todo))))
            (and priority (format "\\framebox{\\#%c} " priority))
            text
            (and tags
            (format "\\hfill{}\\textsc{%s}"
    (mapconcat (lambda (tag) (org-latex-plain-text tag info))
           tags ":")))))

(setq org-latex-format-headline-function 'org-latex-format-headline-colored-keywords-function)
#+end_src

Ignore org comments on export
#+BEGIN_SRC emacs-lisp
  ;; ;; remove comments from org document for use with export hook
  ;; ;; https://emacs.stackexchange.com/questions/22574/orgmode-export-how-to-prevent-a-new-line-for-comment-lines
  ;; (defun delete-org-comments (backend)
  ;;   (cl-loop for comment in (reverse (org-element-map (org-element-parse-buffer)
  ;;                                     'comment 'identity))
  ;;         do
  ;;         (setf (buffer-substring (org-element-property :begin comment)
  ;;                                 (org-element-property :end comment))
  ;;               "")))
  ;; ;; add to export hook
  ;; (add-hook 'org-export-before-processing-hook 'delete-org-comments)
#+END_SRC
*** cdlatex environments
#+BEGIN_SRC emacs-lisp
  ;; (evil-leader/set-key-for-mode 'org-mode "i E" 'cdlatex-environment)
#+END_SRC
*** Syntax highlight
#+BEGIN_SRC emacs-lisp
  (setq org-highlight-latex-and-related '(latex))
#+END_SRC
*** Caption below tables... or not!
#+begin_src emacs-lisp
  ;; (setq org-latex-caption-above nil)
  (setq org-latex-caption-above '(table))
#+end_src
*** ~booktabs~ for tables
#+begin_src emacs-lisp
  (setq org-latex-tables-booktabs t)
#+end_src
*** Code highlighting
#+begin_src emacs-lisp
;; (require 'ox-latex)
;; (add-to-list 'org-latex-packages-alist '("" "minted"))
(setq org-latex-listings 'minted)

;; (setq org-latex-pdf-process
;;       '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
;;         "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
;;         "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
#+end_src
*** No hyperref setup by default
#+begin_src emacs-lisp
  (setq org-latex-with-hyperref nil)
#+end_src
*** Org-ref hotkey
#+begin_src emacs-lisp
  (evil-leader/set-key-for-mode 'org-mode "i R" 'org-ref-insert-ref-link)
#+end_src
** TODO /Zettelkasten/ with ~org-roam~
#+begin_src emacs-lisp
  (setq org-roam-v2-ack t)
#+end_src
*** Set Directory
#+begin_src emacs-lisp
 (setq org-roam-directory "~/org/zettelkasten/")
#+end_src
*** Autosync Mode is needed apparently
#+begin_src emacs-lisp
  (org-roam-db-autosync-mode)
#+end_src
*** Start ~org-roam-mode~ on startup
#+begin_src emacs-lisp
    ;; (add-hook 'after-init-hook 'org-roam-mode)
    ;; (org-roam-setup)
#+end_src
*** Add hotkeys
#+begin_src emacs-lisp
  (spacemacs/declare-prefix "aor" "org-roam")
  (spacemacs/set-leader-keys
    "aorc" 'org-roam-capture
    "aorf" 'org-roam-node-find
    "aori" 'org-roam-node-insert
    "aordD" 'org-roam-dailies-capture-today
    "aordd" 'org-roam-dailies-goto-date
    "aordt" 'org-roam-dailies-goto-today
    "aordT" 'org-roam-dailies-goto-tomorrow
    "aordy" 'org-roam-dailies-goto-yesterday
    )
  (spacemacs/declare-prefix-for-mode 'org-mode "mr" "org-roam")
  (spacemacs/set-leader-keys-for-major-mode 'org-mode
    "rr" 'org-roam-buffer-toggle
    "rc" 'org-roam-capture
    "rf" 'org-roam-node-find
    "ri" 'org-roam-node-insert
    "rdD" 'org-roam-dailies-capture-today
    "rdd" 'org-roam-dailies-goto-date
    "rdt" 'org-roam-dailies-goto-today
    "rdT" 'org-roam-dailies-goto-tomorrow
    "rdy" 'org-roam-dailies-goto-yesterday
    )
#+end_src

*** Capture template
#+begin_src emacs-lisp
  (setq org-roam-capture-templates
        '(
          ("d" "default" plain
           "%?"
           :if-new (file+head "main/%<%Y-%m-%d>-${slug}.org"
                              "#+title: ${title}\n- tags :: \n")
           :unnarrowed t)
          )
        )
#+end_src
*** Capture Ref from Browser
#+begin_src emacs-lisp
  (require 'org-roam-protocol)
#+end_src

#+begin_src emacs-lisp
  (setq org-roam-capture-ref-templates
        (append
         org-roam-capture-ref-templates
         '(("x" "browserref" plain "%?" :if-new
            (file+head "webrefs/%<%Y-%m-%d>-${slug}.org"
                       "#+TITLE: ${title}\n- tags :: \n\n")
            :unnarrowed t))
         ))
#+end_src
*** ~org-roam-bibtex~
#+begin_src emacs-lisp
  (add-hook 'after-init-hook #'org-roam-bibtex-mode)
  (add-hook 'bibtex-mode-hook #'org-roam-bibtex-mode)
#+end_src

#+begin_src emacs-lisp
  ;; (setq orb-templates
  (setq org-roam-capture-templates
        (append
         org-roam-capture-templates
        '(
          ("r" "bibliography reference" plain "%?"
           :if-new
           (file+head "bib/%<%Y-%m-%d>-${slug}.org"
                      "#+title: ${title}\n- source :: ${ref}\n- tags ::")
           :unnarrowed t)
          )
        )
        )
#+end_src
*** ~org-roam dailies~
Directory:
#+begin_src emacs-lisp
 (setq org-roam-dailies-directory "daily/")
#+end_src

Default template:
#+begin_src emacs-lisp
  (setq org-roam-dailies-capture-templates
      '(("d" "default" entry
         "* %?"
         :target (file+head "%<%Y-%m-%d>.org"
                            "#+title: %<%Y-%m-%d>
  ,#+category: %<%Y-%m-%d>
  "))))
#+end_src

Remove the weird hook that colors my calendar:
#+begin_src emacs-lisp
  (with-eval-after-load 'org-roam-dailies
    (remove-hook 'calendar-today-visible-hook #'org-roam-dailies-calendar-mark-entries)
    (remove-hook 'calendar-today-invisible-hook #'org-roam-dailies-calendar-mark-entries))
#+end_src

#+begin_src emacs-lisp
  (setq org-roam-dailies-capture-templates
      '(("d" "default" entry
         "* %?"
         :target (file+head "%<%Y-%m-%d>.org"
                            "#+title: %<%Y-%m-%d>
  ,#+category: %<%Y-%m-%d>

  ,#+begin_src emacs-lisp :results none
    (org-map-entries (lambda () (org-schedule nil \"%<%Y-%m-%d>\")) \"/TODO\")
  ,#+end_src

  * TODOs
  ** TODO
  "))))
#+end_src

Perhaps in the future I want something like this:
#+begin_src emacs-lisp
  ;; (setq org-roam-dailies-capture-templates
  ;;     '(("d" "default" entry
  ;;        "* %?"
  ;;        :target (file+head "%<%Y-%m-%d>.org"
  ;;                           "#+title: %<%Y-%m-%d>
  ;; #+category: %<%Y-%m-%d>


  ;; * Daily journaling
  ;; _Zum Vortag:_


  ;; _Dafür bin ich dankbar:_


  ;; _Darauf bin ich stolz:_


  ;; _Das habe ich gelernt:_


  ;; _Top-3 Energy Givers:_
  ;; 1.
  ;; 2.
  ;; 3.

  ;; _Top-3 Energy Thieves:_
  ;; 1.
  ;; 2.
  ;; 3.

  ;; _Top-3 todos for today:_
  ;; 1.
  ;; 2.
  ;; 3.

  ;; _Darauf bin ich heute neugierig:_

  ;; "))))
#+end_src
** Drop-down org-roam-dailies via [[https://github.com/alphapapa/yequake][~yequake~]]
#+begin_src emacs-lisp
  (setq yequake-frames
        '(("my_yequake_emacs_frame" .
           ((width . 0.75)
            (height . 0.5)
            (alpha . 0.95)
            (buffer-fns . (
                           ;; "~/org/todo.org"
                           ;; split-window-horizontally
                           ;; "*scratch*"
                           org-roam-dailies-goto-today
                           ))
            (frame-parameters . ((undecorated . nil)))))
          ))
#+end_src

This should be paired with the following i3 config
#+begin_src
  for_window [title="my_yequake_emacs_frame"] floating enable, resize set 900 600, move position center, move scratchpad
  bindsym F12 exec --no-startup-id ~/scripts/yequake.sh
#+end_src

and the following callable .sh script
#+begin_src sh
  #!/bin/bash

  if ! xdotool search --name my_yequake_emacs_frame &>/dev/null; then
      emacsclient -n -e '(yequake-toggle "my_yequake_emacs_frame")'
      sleep 0.3
  fi

  i3-msg '[title="my_yequake_emacs_frame"] scratchpad show'

#+end_src
** ~org-hide-drawers~
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-hide-drawers-mode)
#+end_src

#+begin_src emacs-lisp
  (evil-leader/set-key-for-mode 'org-mode "T d" 'org-hide-drawers-toggle)
  (evil-leader/set-key "a o T d" 'org-hide-drawers-toggle)
#+end_src
* Other Packages / Languages / Concepts
** Manage my Email with ~mu4e~
*** Contexts
#+BEGIN_SRC emacs-lisp
  (setq mu4e-contexts
        `(
          ,(make-mu4e-context
            :name "g @gmail"
            :match-func (lambda (msg) (when msg
                                        (string-prefix-p "/Gmail" (mu4e-message-field msg :maildir))))
            :vars '(
                    (user-mail-address . "nathanael.bosch@gmail.com")
                    (user-full-name . "Nathanael Bosch")
                    (mu4e-trash-folder . "/Gmail/[Google Mail].Bin")
                    (mu4e-refile-folder . "/Gmail/[Google Mail].Archive")
                    (mu4e-sent-folder . "/Gmail/[Google Mail].Sent Mail")
                    (mu4e-drafts-folder . "/Gmail/[Google Mail].Drafts")
                    ))
          ,(make-mu4e-context
            :name "u @uni-tue"
            :match-func (lambda (msg) (when msg
                                        (string-prefix-p "/UniTue" (mu4e-message-field msg :maildir))))
            :vars '(
                    (user-mail-address . "nathanael.bosch@uni-tuebingen.de")
                    (user-full-name . "Nathanael Bosch")
                    (mu4e-trash-folder . "/UniTue/Mail.trash")
                    (mu4e-sent-folder . "/UniTue/Mail.sent")
                    (mu4e-drafts-folder . "/UniTue/Mail.drafts")
                    ))
          ,(make-mu4e-context
            :name "e @epfl"
            :match-func (lambda (msg) (when msg
                                        (string-prefix-p "/EPFL" (mu4e-message-field msg :maildir))))
            :vars '(
                    (user-mail-address . "nathanael.bosch@epfl.ch")
                    (user-full-name . "Nathanael Bosch")
                    (mu4e-trash-folder . "/EPFL/Deleted Items")
                    (mu4e-sent-folder . "/EPFL//Sent Items")
                    (mu4e-drafts-folder . "/EPFL/Drafts")
                    ))
          ,(make-mu4e-context
            :name "m @mpi-is"
            :match-func (lambda (msg) (when msg
                                        (string-prefix-p "/MPI-IS" (mu4e-message-field msg :maildir))))
            :vars '(
                    (user-mail-address . "nathanael.bosch@tuebingen.mpg.de")
                    (user-full-name . "Nathanael Bosch")
                    (mu4e-trash-folder . "/MPI-IS/Trash")
                    (mu4e-sent-folder . "/MPI-IS/Sent")
                    (mu4e-drafts-folder . "/MPI-IS/Drafts")
                    ))
          ,(make-mu4e-context
            :name "p @pm.me"
            :match-func (lambda (msg) (when msg
              (and
               (string-prefix-p "/Protonmail" (mu4e-message-field msg :maildir))
               (not (mu4e-message-contact-field-matches msg '(:to :cc :from) "{{@@ env["pm2"] @@}}"))
               )))
            :vars '(
                    (user-mail-address . "nathanael.bosch@pm.me")
                    (user-full-name . "Nathanael Bosch")
                    (mu4e-trash-folder . "/Protonmail/Trash")
                    (mu4e-sent-folder . "/Protonmail/Sent")
                    (mu4e-drafts-folder . "/Protonmail/Drafts")
                    ))
          ,(make-mu4e-context
            :name "s pm2"
            :match-func (lambda (msg) (when msg
              (and
               (string-prefix-p "/Protonmail" (mu4e-message-field msg :maildir))
               (mu4e-message-contact-field-matches msg '(:to :cc :from) "{{@@ env["pm2"] @@}}")
               )))
            :vars '(
                    (user-mail-address . "{{@@ env["pm2"] @@}}")
                    (user-full-name . "{{@@ env["pm2name"] @@}}")
                    (mu4e-trash-folder . "/Protonmail/Trash")
                    (mu4e-sent-folder . "/Protonmail/Sent")
                    (mu4e-drafts-folder . "/Protonmail/Drafts")
                    ))
          ))
#+END_SRC

*** Send Emails
#+BEGIN_SRC emacs-lisp
  (setq mail-user-agent 'mu4e-user-agent  ; set mua header in mails
        message-sendmail-extra-arguments '("--read-envelope-from")
        message-sendmail-f-is-evil t
        message-sendmail-function 'message-sendmail-with-sendmail
        send-mail-function 'message-send-mail-with-sendmail
        sendmail-program "sendmail"
        message-kill-buffer-on-exit t     ; kill old messages when sent
        message-send-mail-function 'message-send-mail-with-sendmail
        message-forward-before-signature nil
        message-cite-reply-position 'above
        org-mu4e-convert-to-html t
  )
#+END_SRC

*** Notifications for new Email
#+begin_src emacs-lisp
  ;; (mu4e-alert-set-default-style 'libnotify)
#+end_src

*** Custom key for update index
#+begin_src emacs-lisp
  (with-eval-after-load 'mu4e
    (define-key mu4e-main-mode-map (kbd "u") 'mu4e-update-index))
#+end_src

*** Custom date format
#+begin_src emacs-lisp
    (setq mu4e-headers-date-format "%d/%m/%Y")
#+end_src

** Writeroom                                                           :WIP:
My goal here: Create a /beautiful/ writing environment!
#+begin_src emacs-lisp
  (setq
   ;; writeroom-maximize-window t
   ;; writeroom-fullscreen-effect nil
   ;; writeroom-extra-line-spacing 0.3
   writeroom-width 88
   writeroom-border-width 30
   )
#+end_src

No line numbers
#+begin_src emacs-lisp
  ;; (defun my/writeroom-without-linenumbers (arg)
  ;;   (cond
  ;;    ((= arg 1)
  ;;     (spacemacs/toggle-line-numbers-off))
  ;;    ((= arg -1)
  ;;     (spacemacs/toggle-line-numbers-on))))

  ;; (add-to-list 'writeroom-global-effects 'my/writeroom-without-linenumbers)
#+end_src

Enable some nice white Theme
#+begin_src emacs-lisp
  ;; (setq my/main-theme 'gruvbox)
  ;; (setq my/writeroom-theme 'leuven)
  ;; (load-theme my/writeroom-theme)
  ;; (disable-theme my/writeroom-theme)
  ;; (load-theme my/main-theme)
  ;; (defun my/writeroom-theme-fn (arg)
  ;;   (cond
  ;;    ((= arg 1)
  ;;     (enable-theme my/writeroom-theme)
  ;;     (disable-theme my/main-theme)
  ;;     )
  ;;    ((= arg -1)
  ;;     (disable-theme my/writeroom-theme)
  ;;     (enable-theme my/main-theme)
  ;;     )
  ;;    ))
  ;; (add-to-list 'writeroom-global-effects 'my/writeroom-theme-fn)
#+end_src

** Make windows more narrow and centered for more aesthetics           :WIP:
#+begin_src emacs-lisp
  (setq visual-fill-column-center-text t)
  (setq visual-fill-column-width 88)
  (add-hook 'org-mode-hook 'visual-fill-column-mode)
  (add-hook 'typst-ts-mode-hook 'visual-fill-column-mode)
#+end_src
** ~magit~ - The best git interface
Start in Evil mode
#+BEGIN_SRC emacs-lisp
  ;; Start magit commit in insert mode
  (add-hook 'with-editor-mode-hook 'evil-insert-state)
#+END_SRC

Magit blame keys
#+begin_src emacs-lisp
  (global-set-key (kbd "C-c b") 'magit-blame)
#+end_src

Refine diffs
#+begin_src emacs-lisp
  (setq magit-diff-refine-hunk "all")
#+end_src

Set MAGIT visibility to
#+begin_src emacs-lisp
  (setq forge-topic-list-limit '(15 . 0))
#+end_src

*** Add uni-tuebingen gitlab
#+begin_src emacs-lisp
  ;; (add-to-list 'forge-alist
  ;;              '("gitlab.mlcloud.uni-tuebingen.de" "gitlab.mlcloud.uni-tuebingen.de/api/v4" "gitlab.mlcloud.uni-tuebingen.de" forge-gitlab-repository)
  ;;              )
#+end_src

** LaTeX
Ask me about the TeX master file if unsure
#+BEGIN_SRC emacs-lisp
  (setq-default TeX-master nil)
#+END_SRC
*** RefTex
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key-for-mode 'latex-mode "r r" 'reftex-cleveref-cref)
  (evil-leader/set-key-for-mode 'latex-mode "r t" 'reftex-citet)
  (evil-leader/set-key-for-mode 'latex-mode "r p" 'reftex-citep)
#+END_SRC
*** Helm-bibtex for citations
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key-for-mode 'latex-mode "B" 'helm-bibtex-with-local-bibliography)

  ;; (helm-delete-action-from-source "Insert BibTeX entry" helm-source-bibtex)
  ;; (helm-add-action-to-source "Insert BibTeX entry" 'helm-bibtex-insert-bibtex helm-source-bibtex 0)
#+END_SRC
*** Outline Minor Mode
#+BEGIN_SRC emacs-lisp
  (add-hook 'LaTeX-mode-hook 'outline-minor-mode)
#+END_SRC

Fake sections for better manipulation:
#+BEGIN_SRC emacs-lisp
  (setq TeX-outline-extra
        '(("%chapter" 1)
          ("%section" 2)
          ("%subsection" 3)
          ("%subsubsection" 4)
          ("%paragraph" 5)))
  ;; add font locking to the headers
  (font-lock-add-keywords
   'latex-mode
   '(("^%\\(chapter\\|\\(sub\\|subsub\\)?section\\|paragraph\\)"
      0 'font-lock-keyword-face t)
     ("^%chapter{\\(.*\\)}"       1 'font-latex-sectioning-1-face t)
     ("^%section{\\(.*\\)}"       1 'font-latex-sectioning-2-face t)
     ("^%subsection{\\(.*\\)}"    1 'font-latex-sectioning-3-face t)
     ("^%subsubsection{\\(.*\\)}" 1 'font-latex-sectioning-4-face t)
     ("^%paragraph{\\(.*\\)}"     1 'font-latex-sectioning-5-face t)))
#+END_SRC
*** Outline-magic
#+BEGIN_SRC emacs-lisp
  (define-key outline-minor-mode-map (kbd "<C-tab>") 'outline-cycle)
  (define-key outline-minor-mode-map (kbd "M-h") 'outline-promote)
  (define-key outline-minor-mode-map (kbd "M-j") 'outline-move-subtree-down)
  (define-key outline-minor-mode-map (kbd "M-k") 'outline-move-subtree-up)
  (define-key outline-minor-mode-map (kbd "M-l") 'outline-demote)
  (define-key outline-minor-mode-map (kbd "M-H")
    (lambda() (interactive) (evil-visual-line) (outline-promote)))
  (define-key outline-minor-mode-map (kbd "M-L")
    (lambda() (interactive) (evil-visual-line) (outline-demote)))
#+END_SRC
*** Visual fill mode instead of auto fill
#+BEGIN_SRC emacs-lisp
  (add-hook 'LaTeX-mode-hook 'visual-fill-column-mode)
  ;; (add-hook 'LaTeX-mode-hook 'spacemacs/toggle-auto-fill-mode-off)
#+END_SRC
*** Beamer: Bold as bold, not as alert!
#+begin_src emacs-lisp
  (defun my-beamer-bold (contents backend info)
    (when (eq backend 'beamer)
      (replace-regexp-in-string "\\`\\\\[A-Za-z0-9]+" "\\\\textbf" contents)))

  (add-to-list 'org-export-filter-bold-functions 'my-beamer-bold)
#+end_src

** YASnippet
Add the yasnippet-snippets snippets to YASnippet.
#+begin_src emacs-lisp
  ;; (add-to-list 'yas-snippet-dirs yasnippet-snippets-dir)
#+end_src

Use YASnippet in ~ledger-mode~
#+begin_src emacs-lisp
  (add-hook 'ledger-mode-hook 'yas-minor-mode)
#+end_src
** Budget money with ~ledger-cli~
#+begin_src emacs-lisp
  (setq org-capture-templates
        (append
         org-capture-templates
         '(("l" "Ledger entries")
           ("lr" "Rewe" plain (file "~/MEGA/finances.ledger")
            "%(org-read-date) Rewe Einkauf
      Expenses:Food:Groceries     %^{Amount}
      Assets:Volksbank
    ")
           ;; ("lc" "Cash" plain (file "~/MEGA/finances.ledger")
           ;;  "%(org-read-date) * %^{Payee}
           ;;   Expenses:%^{Account}  %^{Amount}
           ;;   Expenses:Cash
           ;; ")
           )
         ))
#+end_src
** Grammar checking with LanguageTool
#+begin_src emacs-lisp
  (setq langtool-default-language "en-US")
  (setq langtool-bin "/usr/bin/languagetool")
#+end_src
** Julia
*** Julia block
#+begin_src emacs-lisp
  ;; Type <j then tab key to create julia src block
  (add-to-list 'org-structure-template-alist '("j" . "src julia"))
#+end_src

#+begin_src emacs-lisp
  ;; Type <jj then tab key to create jupyter-julia src block
  (add-to-list 'org-structure-template-alist '("jj" . "src jupyter-julia"))
#+end_src
*** Add .jmd to markdown-mode
#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.jmd\\'" . markdown-mode))
#+end_src
** Bugfix TRAMP
Faster than the default scp:
#+begin_src emacs-lisp
  (setq tramp-default-method "ssh")
#+end_src
** Fira Code Ligatures

#+begin_src emacs-lisp
  (fira-code-mode-set-font)
  ;; (setq 'fira-code-mode-disabled-ligatures '("x"))
  (add-hook 'prog-mode-hook 'fira-code-mode)
  (add-hook 'org-mode-hook 'fira-code-mode)
  (add-hook 'org-agenda-mode-hook 'fira-code-mode)
#+end_src

** Github copilot

#+begin_src emacs-lisp
  ;; (with-eval-after-load 'company
  ;;   ;; disable inline previews
  ;;   (delq 'company-preview-if-just-one-frontend company-frontends))

  (with-eval-after-load 'copilot
    (define-key copilot-completion-map (kbd "<tab>") 'copilot-accept-completion)
    (define-key copilot-completion-map (kbd "TAB") 'copilot-accept-completion)
    (define-key copilot-completion-map (kbd "C-TAB") 'copilot-accept-completion-by-word)
    (define-key copilot-completion-map (kbd "C-<tab>") 'copilot-accept-completion-by-word)
    )

  (add-hook 'prog-mode-hook 'copilot-mode)
  (add-hook 'LaTeX-mode-hook 'copilot-mode)

  ;; (define-key evil-insert-state-map (kbd "C-<tab>") 'copilot-accept-completion-by-word)
  ;; (define-key evil-insert-state-map (kbd "C-TAB") 'copilot-accept-completion-by-word)

  (define-key evil-insert-state-map (kbd "M-n") 'copilot-next-completion)
#+end_src
** Firefox as default browser
#+begin_src emacs-lisp
  (setq browse-url-browser-function 'browse-url-firefox)
#+end_src
** Start atomic-chrome server to use emacs for writing in a browser
#+begin_src emacs-lisp
  (atomic-chrome-start-server)
#+end_src
** typst
What I did:
- Install tree-sitter
- Run `treesit-install-language-grammar`
- Enter `typst` and point it to the grammar source url:
  https://github.com/uben0/tree-sitter-typst

I also have this, but not sure if it
#+begin_src emacs-lisp
  (with-eval-after-load 'eglot
    (with-eval-after-load 'typst-ts-mode
      (add-to-list 'eglot-server-programs
                   `((typst-ts-mode) .
                     ,(eglot-alternatives `(,typst-ts-lsp-download-path
                                            "tinymist"
                                            "typst-lsp"))))))
#+end_src
** ~agent-shell~
See https://github.com/xenodium/agent-shell
#+begin_src emacs-lisp
  (require 'agent-shell-anthropic)

  (setq agent-shell-container-command-runner '("claude-sandbox" "--exec"))

  (setq agent-shell-preferred-agent-config  (agent-shell-anthropic-make-claude-code-config))

  (advice-add 'agent-shell--image-type-to-mime :before-while
               (lambda (file) file))
#+end_src
*** Project agent shell opener with helm
#+begin_src emacs-lisp
  (defun my/helm-agent-shell-project ()
    "Select a project via Helm and start agent-shell there."
    (interactive)
    (helm :sources
          (helm-build-sync-source "Projects"
            :candidates #'projectile-relevant-known-projects
            :action (lambda (project)
                      (let ((default-directory project))
                        (agent-shell))))
          :buffer "*helm agent-shell*"))

  (spacemacs/set-leader-keys "pa" #'my/helm-agent-shell-project)
#+end_src
** ~vterm~
*** Always open a fresh vterm when calling ~vterm~
#+begin_src emacs-lisp
  (advice-add 'vterm :filter-args
              (lambda (args) (list (or (car args) t))))
#+end_src
*** No modeline
#+begin_src emacs-lisp
  (add-hook 'vterm-mode-hook
          (lambda ()
            (setq-local mode-line-format nil)))
#+end_src
*** Gruvbox colors
#+begin_src emacs-lisp
(custom-set-faces
 '(term-color-black   ((t (:foreground "#282828" :background "#282828"))))
 '(term-color-red     ((t (:foreground "#cc241d" :background "#cc241d"))))
 '(term-color-green   ((t (:foreground "#98971a" :background "#98971a"))))
 '(term-color-yellow  ((t (:foreground "#d79921" :background "#d79921"))))
 '(term-color-blue    ((t (:foreground "#458588" :background "#458588"))))
 '(term-color-magenta ((t (:foreground "#b16286" :background "#b16286"))))
 '(term-color-cyan    ((t (:foreground "#689d6a" :background "#689d6a"))))
 '(term-color-white   ((t (:foreground "#a89984" :background "#a89984")))))
#+end_src
*** Font fix
#+begin_src emacs-lisp
  ;; (set-fontset-font t '(#xf0000 . #xfffff) "FiraCode Nerd Font")
  ;; (set-fontset-font t '(#xe000 . #xf8ff) "FiraCode Nerd Font Mono")
#+end_src
** ~dirvish~
#+begin_src emacs-lisp
  (dirvish-override-dired-mode)
  (spacemacs/set-leader-keys "aD" 'dirvish)
  (require 'dired-x)
  (setq dired-omit-files (concat dired-omit-files "\\|^\\..+$"))
  (setq dired-listing-switches "-AGhlv --group-directories-first")
  (add-hook 'dired-mode-hook #'dired-omit-mode)

  (with-eval-after-load 'dired
    (evilified-state-evilify-map dired-mode-map
      :mode dired-mode
      :bindings
      "h"         'dired-up-directory
      "l"         'dired-find-file
      "q"         'dirvish-quit
      "/"         'dirvish-narrow
      "gr"        'revert-buffer
      "."         'dired-omit-mode
      (kbd "TAB") 'dirvish-subtree-toggle
      "f"         'dirvish-layout-toggle
      "gd"        'dirvish-dispatch
      "pp"        'dirvish-yank
      "pm"        'dirvish-move
      ))
#+end_src
